### ISSUE TITLE
Working good

### ISSUE THREAD

**Issue by 417Goose** [greghesp/assistant-relay#1]
Working pretty good ... I have it announce when our heat comes on and has been working flawlessly.

If we could get it  to work more like a "location Send and SMS message" it may make it easier to integrate into webcore stuff instead of a switch.

Good job so far !

Looking into it a bit.

**Comment by greghesp** [comment]
Can you explain what you mean a bit more?

The integration into webcore should work if you add the SmartApp and DTH.  
You can select the Assistant Relay as a device, select a capability and then choose a parameter
