### ISSUE TITLE
"Looks like there aren't any other speakers connected to your home network"

### ISSUE THREAD

**Issue by DennisMamedov** [greghesp/assistant-relay#100]
When I try to run the example "hello world" request, it responds an url leading to an audio file (nothing plays on my speaker). When I open that audio file it simply is the google lady saying: "Looks like there aren't any other speakers connected to your home network, so I can't broadcast your message". The response says "success : true", even though I don't hear anything.

I'm running the program on a Raspberry Pi 3B+, on the same network as my Google Home (which works normally).
How do I go about getting the program working?

The R.Pi console prints this:

```
Received command broadcast hello world 

User specified was dennis 

Conversation Complete
```

EDIT: Just checked my Google API dashboard and it acknowledged the requests, but it failed 100% of them. I can't find some kind of error description, but it does say that all requests failed.

**Comment by WilliamFisher** [comment]
Similar issue here except my audio response says "Ok broadcasting now". No broadcast plays and I am seeing a 100% error rate in the Google API dashboard.

**Comment by ryancasler** [comment]
Have you tried disabling IPv6 on your network?

**Comment by WilliamFisher** [comment]
@ryancasler Any possible workaround for this? I don't believe I can disable IPv6 on my router. Should this not be accounted for as IPv6 is pretty standard today?

**Comment by samsonusmc** [comment]
I am getting the exact same behavior. Everything looks good on the RPI but GCP says 100% fail. IPv6 is off on my network (now). No Broadcast, no errors.

**Comment by samsonusmc** [comment]
@WilliamFisher did you get yours working? My audio response is "Got it broadcasting now" but silence.

**Comment by WilliamFisher** [comment]
@samsonusmc No. I wasn’t able to disable IPv6 so it’s not likely to work. I just decided to use pychromecast instead. Even though it requires more work it’s really my only option.
  

  
>

**Comment by ghust** [comment]
But that doesn't allow you to broadcast, does it? 

I'd like to use this assistant relay because I don't want music interruptions anymore... I'll keep digging :)

**Comment by otaviojr** [comment]
Same thing here.  Trying to make it work, but, no success...

**Comment by ryancasler** [comment]
GCP will always display 100% failure.  It says the same thing for me.  All I can say is that you have to make sure the same account you used in the Google Console is the one linked to your GH speakers.  Make sure IPv6 is off on your router.  And make sure that all the devices are on the same network (and your netmask is correct).  It is working for me, so absent any logs, I don't know of any other tricks.  Sorry.

**Comment by greghesp** [comment]
If you're getting a response from Google, then Assistant Relay is doing its part of the job. 
You;ve likely not got something setup correctly either with your Google account, or when downloading the client secret file from Google (maybe wrong account signed in?)
