### ISSUE TITLE
Nothing happens on any device

### ISSUE THREAD

**Issue by Keiishu** [greghesp/assistant-relay#101]
I am on NodeJS 8.16 as recommended, I have disabled IPv6 on my RPi as said in #55 and #74, but nothing is happening on my Google Home even if the relay returns `success=true`.

Does someone have any idea on how to actually get it working?

**Comment by ryancasler** [comment]
You have to delete IPv6 support on your router.  If the Google Home devices are able to get an IPv6 address, that is what they will use to identify if they are on the same network and available to be broadcast to.  Trying disabling it on your router and see what happens.

**Comment by Keiishu** [comment]
I can't disable IPv6 myself on my router unfortunately. I'll try to ask my FAI when I have time.
Thanks for your help!
