### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OkiRules** [greghesp/assistant-relay#105]
Hi,

I configured all the files like in the readme and when I try to to go the link in Safari I get this error: 

`Cannot GET /`

Thanks

**Comment by mike9900** [comment]
I also experience this. However, it is still working. You can use postman to send some json data to it to see if it works.

**Comment by OkiRules** [comment]
Its not working and there is no output in Terminal.

**Comment by OkiRules** [comment]
Its not even saying that Assistant Relay is setup.

**Comment by PaRkThEcAr** [comment]
did anyone find an answer to this? i am having the same issue. @greghesp, do you know how to solve the "cannot get /" error?

**Comment by ryancasler** [comment]
Try the fix I listed here:
https://github.com/greghesp/assistant-relay/issues/108#issuecomment-539109272

**Comment by PaRkThEcAr** [comment]
For me, I was able to get the auth url to work. But after linking things up, the suggested url to view the service in (http://MY.IP:PORT <http://my.ip:port>) only responds with a "cannot get /“ error. I believe that the service still works but as I am currently at work and not at home I am unable to verify.

My goal is to use this in conjunction with HTTP switches in HomeBridge to automate broadcasting. 

If the HTTP switches still work but that page refuses to load, would this need to be something I analyze further? Or is the “cannot get /“ error normal?

**Comment by ryancasler** [comment]
Well, the HTTP endpoints require POST messages.  So, I'm not surprised that they didn't respond to GET messages.  There's examples of the POST message requirements on the front page of the repo.

**Comment by greghesp** [comment]
Ignore the /GET message.  It's all /POST based.  
I think a merge or a pull must have gone wrong somewhere.  I'm writing a version 3 at the moment to address the bugs and shortcomings. 
Hopefully it will be out soon

**Comment by PaRkThEcAr** [comment]
Greg, when do we expect to see an update to Assistant Relay?
