### ISSUE TITLE
Cannot GET /customBroadcast

### ISSUE THREAD

**Issue by creed205** [greghesp/assistant-relay#11]
When I try to perform the test as listed in the instructions, I am receiving an error in my browser window:
Cannot GET /customBroadcast
The service is working (installed on my Ubuntu server) because when I execute it, it plays the audio stating that it's operational. I simply can not make calls to the api.
Any help would be appreciated.

**Comment by bendews** [comment]
customBroadcast requires a POST request, rather than a GET. You will have to use a tool like Postman or try a curl request from the device you have assistant-relay installed on:
```
curl -d "text=Testing%20A%20Broadcast" -X POST http://localhost:3000/customBroadcast
```

**Comment by naseemr** [comment]
Hi Greg, I tried the command ball and still getting error.
curl -d "text= hello" -X POST http://localhost:3000/customBroadcast

Received command broadcast undefined
No user specified, using naseemra
{"message":"Custom broadcast command executed","command":"broadcast undefined"}
