### ISSUE TITLE
Native Language

### ISSUE THREAD

**Issue by strategiamkt** [greghesp/assistant-relay#111]
Is it possible to change the native language that Google Assistant Relay uses to communicate with Google Home? My GH is set to Portuguese (BR) but when I send commands from relay the answers came in English and it is a problem to me because I use a lot of broadcast commands. Even if I send the command in Portuguese, GH activates English voice and it ends in a terrible result. Thanks

**Comment by greghesp** [comment]
Which version are you using?

**Comment by strategiamkt** [comment]
Thanks a lot Greg. I changed there and the answer (audio) on Relay changed to portuguese (perfect!), but GH still keeps answering on English voice. Is there any other place that I should change? Tks

**Comment by greghesp** [comment]
When you say "it keeps answering on English voice", do you mean broadcasts are spoken using the English assistant, or is this in the audio file returned?

**Comment by strategiamkt** [comment]
Broadcasts are spoken using the English assistant, while audio file returns using the Portuguese assistant.

**Comment by greghesp** [comment]
Daft question, but are you broadcasting a sentence in English?  broadcast will literally broadcast whatever text you send to it

**Comment by greghesp** [comment]
You need to configure you Google Home's then on the GH App as thats nothing to do with Assistant Relay.

As for the command, that might be because the SDK doesn't support it in that language
