### ISSUE TITLE
Is there a config file to change the port? 

### ISSUE THREAD

**Issue by MechEng70** [greghesp/assistant-relay#119]
**Describe the bug**
Due to having other items on this server, is there anyway to move the port from 3000?

**Comment by greghesp** [comment]
You can change the port once its up and running, however that's obviously not going to help you if stuff is already running on 3000.

If you make a file called `config.json` inside the bin folder, and then paste in the following, it should load it on port 3005.  Feel free to swap the value for whatever port you need.

```
{
  "port": 3005
}
```

Let me know how you get on
