### ISSUE TITLE
Update instructions - lower case required when user name is used 

### ISSUE THREAD

**Issue by Danabw** [greghesp/assistant-relay#12]
Update instructions to inform users that when a user name is used in a command, the name must be all lower case. E.g., below in the Custom Broadcast and Custom Command sections. 

Custom Broadcast

with the following parameters:

text: hello world
user: <user in config> 
**user name must be lower case**

Custom commands
If you want to send a custom command to the Google Home (anything that would follow 'OK Google'), use the following request:

http://<ip_address>:3000/custom?command=<custom command>&user=<config file user name>
**user name must be lower case**

**Comment by greghesp** [comment]
Fixed in the relay itself
