### ISSUE TITLE
Dashboard / Setup not working

### ISSUE THREAD

**Issue by derelict** [greghesp/assistant-relay#120]
**Describe the bug**
Dashboard / Initial Setup not working. Only "Google Assistant Sign" shown.
Sometimes i get a message like "We have lost the Server Connection" where i can enter the Server IP and Port .. but still .. i only get the animated Google Assistant Thing

**To Reproduce**
1. Install Ubuntu 18.04
2. Download and unzip latest Release ZIP File (v3.0.2 Beta)
3. npm run setup
4. npm run start
5. access the dashboard on port 3000 from a browser
6. only shows animated google assistant logo

**Expected behavior**
Dashboard or some kind of Wizard showing.

**Screenshots**
![image](https://user-images.githubusercontent.com/2826671/67628985-3f62ab00-f86f-11e9-93fc-3b0039a4cf43.png)

**Desktop (please complete the following information):**
-  Ubuntu 18.04
 - Chrome and Firefox
 - v3.0.2 Beta

**Additional context**

**Comment by derelict** [comment]
with v3.0.1 Beta i get this (using a firefox private window):

![image](https://user-images.githubusercontent.com/2826671/67629127-155eb800-f872-11e9-9e7a-ebf490333f03.png)

**Comment by greghesp** [comment]
@derelict   v3.0.1 had a bug in it which produces all those errors! Oops!

Can you try version v3.0.2 again, as I had to reupload the release.zip
https://github.com/greghesp/assistant-relay/releases/download/v3.0.2b/release.zip

**Comment by derelict** [comment]
Hi

Thank you very much. I can confirm, that the new Version works like a charm!

Thank you very much!
