### ISSUE TITLE
Command "Watch <something> on Netflix" not working

### ISSUE THREAD

**Issue by strategiamkt** [greghesp/assistant-relay#122]
**Describe the bug**
Voice command: Watch <something> on Netflix works perfectly on my GH, but when I send the same command via relay it doesn't.

**To Reproduce**
1. Go to Sandbox
2. Click on command textbox
3. Type "Watch Black Mirror on Netflix"
4. Click on Submit
5. Listen to the audio returned: "Sorry, I can't help with that yet"

**Expected behavior**
Open Netflix on my chromecast and start reproducing Black Mirror

**Screenshots**
No Screenshots

**Desktop (please complete the following information):**
-  Platform: Windows
 - Browser: Chrome
 - Version: 78.0.3904.70
 - Relay version: 3.0.3

**Additional context**
No additional context

**Comment by ryancasler** [comment]
That means that this command is not supported by the Assistant SDK.  Not all of the commands that you can issue to your Google Home/Nest Speakers or to the Assistant on your phone work with Assistant Relay.  For example media controls to another device.  Also, Routines are not supported presently.

**Comment by greghesp** [comment]
Ryan is correct. There are SDK limitations, and unfortunate this is one of them.

**Comment by strategiamkt** [comment]
Ok thank you
