### ISSUE TITLE
Windows server 2016

### ISSUE THREAD

**Issue by joetlawson** [greghesp/assistant-relay#123]
**Describe the bug**
I'm trying to install this on windows server 2016 as I have ran v1 and v2 on this same server. I ran into an issue with some required dependencies not being install. I was able to get that dependency installed and get past that now in the console I see what is pasted below. 

**To Reproduce**
npm run start
Compiled with warnings.

./src/helpers/api.js
  Line 10:11:  'w' is assigned a value but never used  no-unused-vars

./src/views/dash/Sandbox/index.js
  Line 10:12:  'devices' is assigned a value but never used      no-unused-vars
  Line 11:22:  'setDisabled' is assigned a value but never used  no-unused-vars

./src/App.js
  Line 17:8:   'Override' is defined but never used              no-unused-vars
  Line 25:12:  'override' is assigned a value but never used     no-unused-vars
  Line 25:22:  'setOverride' is assigned a value but never used  no-unused-vars

./src/views/dash/Configuration/Users/index.js
  Line 1:26:  'useEffect' is defined but never used  no-unused-vars

./src/views/dash/Configuration/GoogleDevices/index.js
  Line 1:26:  'useEffect' is defined but never used  no-unused-vars

./src/views/dash/Configuration/index.js
  Line 3:9:    'Input' is defined but never used              no-unused-vars
  Line 3:66:   'Icon' is defined but never used               no-unused-vars
  Line 7:8:    'GoogleDevices' is defined but never used      no-unused-vars
  Line 8:8:    'Users' is defined but never used              no-unused-vars
  Line 15:12:  'initGet' is assigned a value but never used   no-unused-vars
  Line 17:12:  'users' is assigned a value but never used     no-unused-vars
  Line 17:19:  'setUsers' is assigned a value but never used  no-unused-vars

./src/views/dash/About/index.js
  Line 43:166:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank

./src/views/dash/Home/index.js
  Line 6:18:  'Button' is defined but never used  no-unused-vars
  Line 6:26:  'Icon' is defined but never used    no-unused-vars
  Line 7:8:   'Sound' is defined but never used   no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
Compiled with warnings.

./src/helpers/api.js
  Line 10:11:  'w' is assigned a value but never used  no-unused-vars

./src/views/dash/Sandbox/index.js
  Line 10:12:  'devices' is assigned a value but never used      no-unused-vars
  Line 11:22:  'setDisabled' is assigned a value but never used  no-unused-vars

./src/App.js
  Line 17:8:   'Override' is defined but never used              no-unused-vars
  Line 25:12:  'override' is assigned a value but never used     no-unused-vars
  Line 25:22:  'setOverride' is assigned a value but never used  no-unused-vars

./src/views/dash/Configuration/Users/index.js
  Line 1:26:  'useEffect' is defined but never used  no-unused-vars

./src/views/dash/Configuration/GoogleDevices/index.js
  Line 1:26:  'useEffect' is defined but never used  no-unused-vars

./src/views/dash/Configuration/index.js
  Line 3:9:    'Input' is defined but never used              no-unused-vars
  Line 3:66:   'Icon' is defined but never used               no-unused-vars
  Line 7:8:    'GoogleDevices' is defined but never used      no-unused-vars
  Line 8:8:    'Users' is defined but never used              no-unused-vars
  Line 15:12:  'initGet' is assigned a value but never used   no-unused-vars
  Line 17:12:  'users' is assigned a value but never used     no-unused-vars
  Line 17:19:  'setUsers' is assigned a value but never used  no-unused-vars

./src/views/dash/About/index.js
  Line 43:166:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank

./src/views/dash/Home/index.js
  Line 6:18:  'Button' is defined but never used  no-unused-vars
  Line 6:26:  'Icon' is defined but never used    no-unused-vars
  Line 7:8:   'Sound' is defined but never used   no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Expected behavior**
The web UI opens but just shows the animated google icons and never goes beyond this part.

**Screenshots**
![image](https://user-images.githubusercontent.com/28049871/68070390-f6659780-fd43-11e9-9777-0530d2c18430.png)

**Desktop (please complete the following information):**
-  Platform Server 2016 
 - Browser Chrome
 - Version V3

**Additional context**
Any help would be appreciated and thanks Greg for all your hard work on this one.

**Comment by greghesp** [comment]
You're trying to build it from source, nothing wrong with that but I suspect it's not what you wanted to do.

Download the latest built release and try that one:
https://github.com/greghesp/assistant-relay/releases/latest

**Comment by joetlawson** [comment]
That worked thanks Greg.
