### ISSUE TITLE
Remote access to Assistant Relay web app not working

### ISSUE THREAD

**Issue by mjarends** [greghesp/assistant-relay#124]
**Describe the bug**
**NOTE:** I am running this on Docker. I updated https://github.com/kmlucy/docker-assistant-relay docker container to use the new v3 branch - see https://github.com/mjarends/docker-assistant-relay.

When I try to access the Assistant Relay web app from a remote system on my network I keep getting the "Whoops! We lost your server connection" error.

**To Reproduce**
1. Go to `http://<assistant relay host name>:<assistant relay port number>/`
2. Fill in the server's IP address and port number and click Save
3. The "Whoops! We lost your server connection" page comes back up and I am not forwarded into the Home page

**Expected behavior**
On step 3 I would have expected to be forwarded to the Assistant Relay Home page 

**Screenshots**
![lost-connection](https://user-images.githubusercontent.com/4975514/68090963-b388ea00-fe3f-11e9-8576-ad8d554c938c.PNG)

**Desktop (please complete the following information):**
-  Platform: Docker 19.03.4 running on Windows 10
 - Browser Chrome 77.0.3865.120
 - Version: Assistant Relay 3.0.3

**Comment by ryancasler** [comment]
I just build a docker image for GAR myself.  Are you exposing port 3000 in your Dockerfile and are you then making sure that port is exposed when you ran your "docker run" command?

**Comment by mjarends** [comment]
Dockerfile is here: https://github.com/mjarends/docker-assistant-relay/blob/v3/Dockerfile

The actual deploy was done thru Portainer using the following options:

```
docker volume create assistant-relay-config-json
docker volume create assistant-relay-audio-response

docker run \
  -p 3000:3000 \
  -v assistant-relay-config-json:/assistant-relay/relay/bin \
  -v assistant-relay-audio-response:/assistant-relay/relay/bin/audio-responses \
  mjarends/docker-assistant-relay
```

The app works perfectly fine and I can access the web interface from the Windows 10 box where it is running by going to http://localhost:3000. My issue is that I can't access the web interface from other PCs/devices within my network.

**Comment by ryancasler** [comment]
I'm not sure why you're doing the volumes.  I guess I just don't know enough about docker.  All i know is that what I did works and I can access GAR from any pc on my network.

**Comment by mjarends** [comment]
I created volumes is so that the data is persisted between destroy/recreates of the containers. If you want to update and you are not storing the data external to the container you will need to reconfigure GAR each time.

I notice that you are on node v10.x. My docker container is on v8.x. I will try bumping the version to the LTS to see if that resolves the issue.

**Comment by mjarends** [comment]
I was able to get this to work but I had to modify the ip and port properties in Local Storage using Developer Tools in Chrome. After trying to access the remote server I did the following:
* In Chrome, opened **Developer Tools** (F12)
* Click on **Application > Local Storage** and change ip = `<server IP address>` and port = `<port number>`
* Refresh the web page and it will load

**Comment by greghesp** [comment]
Glad to hear you got it working. It stores the details in local storage, as in development I couldn't get the environment to work as it runs on its own build server, whereas for the actual release it's built and is hosted by the express server.

I've had that issue before, but I was pretty sure I had fixed it.

**Comment by mjarends** [comment]
I built the initial Docker container over the weekend so it would have pulled the latest code. I also re-built yesterday using Node.js 10.x.

Is there a change I could look for to verify that it's in my version?

**Comment by greghesp** [comment]
No changes in the version you used. Did you manage to sort this?

**Comment by mjarends** [comment]
I'm still having the issue. I updated the docker image again to fix an issue I had with the volume mounts but the issue still exists.

**Comment by greghesp** [comment]
I can't get your Docker image to run, however I think thats a lack of Docker experience on my behalf.  I created a directory called `docker-ar` and created the 2 folders in it.  Added the Dockerfile in there too, and then ran `docker build -t "ar:Dockerfile" .`

That all worked fine, however I can't get the docker run command to work
`docker run -d -p 3000:3000 --name ar --restart always -v  C:/Users/Greg/Downloads/docker-ar/config/config.json:/assistant-relay/relay/bin/config.json -v  C:/Users/Greg/Downloads/docker-ar/audio-responses:/assistant-relay/relay/bin/audio-responses \mjarends/docker-assistant-relay`

Throws and error saying `'mjarends' is not a recognised command`

**Comment by mjarends** [comment]
I'm assuming you enabled C: as a shared drive on your PC where you are
running Docker and you are using Linux containers for Windows.

If you want to use your local build you will need to change the docker run
command to use your tag:

docker run -d -p 3000:3000 --name ar --restart always -v
C:/Users/Greg/Downloads/docker-ar/config/config.json:/
assistant-relay/relay/bin/config.json -v C:/Users/Greg/Downloads/
docker-ar/audio-responses:/assistant-relay/relay/bin/audio-responses
ar:Dockerfile

If you want to use my build remove the extra slash before \mjarends:

docker run -d -p 3000:3000 --name ar --restart always -v
C:/Users/Greg/Downloads/docker-ar/config/config.json:/
assistant-relay/relay/bin/config.json -v C:/Users/Greg/Downloads/
docker-ar/audio-responses:/assistant-relay/relay/bin/audio-responses
mjarends/docker-assistant-relay

**Comment by ryancasler** [comment]
My image is a lot simpler than that.  Just run:

docker run -p 3000:3000 --name assistant-relay ryan780/assistant-relay-v3

That will pull the latest docker image and run it as a container called assistant-relay and expose port 3000 on your bridged network.  To get to your GAR dashboard, just navigate to the IP of your server followed by the port you exposed, in this case 3000.  If you wanted an alternate port, of 3001 for example, you would use:

docker run -p 3001:3000 --name assistant-relay ryan780/assistant-relay-v3

And that would use port 3001.

**Comment by ryancasler** [comment]
All of this:

 -v
C:/Users/Greg/Downloads/docker-ar/config/config.json:/
assistant-relay/relay/bin/config.json -v C:/Users/Greg/Downloads/
docker-ar/audio-responses:/assistant-relay/relay/bin/audio-responses
ar:Dockerfile

Isn't necessary unless you want to get the audio response files back from GAR.  However, you can just play them from the dashboard and they work just fine.

**Comment by ryancasler** [comment]
I have had to move the image to a new name.  It's now on docker hub under google-assistant-relay instead.

**Comment by greghesp** [comment]
Did you get this working?

**Comment by mjarends** [comment]
I deployed 3.0.5 and the issue is resolved for me. Thanks!
