### ISSUE TITLE
Deprecated jade libraries in use in 'relay' part

### ISSUE THREAD

**Issue by Webunity** [greghesp/assistant-relay#125]
**Describe the bug**
Deprecated libraries in use

**To Reproduce**
npm i

```
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
```

And some more issues; but these seem to be related to external libraries in use.
```
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
```

**Comment by greghesp** [comment]
These are just warnings so you can ignore them. They're not actually used by AR directly, but are part of the Express library

https://github.com/expressjs/express/issues
