### ISSUE TITLE
Emoji Are Read Aloud in Converse Response

### ISSUE THREAD

**Issue by ryancasler** [greghesp/assistant-relay#127]
When issuing a command where GA responds with an Emoji in the answer, for example, "Tell me a joke." if the response contains an emoji, when that is broadcast to other GH devices, the emoji is read aloud rather than being dropped.  For example, this command:
{
"user": "ryan",
"command": "Tell me a joke.",
"converse": true,
"broadcast": false
}

Resulted in this response on the dashboard of GAR:
What happens when a frog's car breaks?
It gets toad 🐸

And a broadcast of:  "Broadcast from Ryan.  What happens when a frog's car breaks?  It gets toad toad face."

The emoji is spoken aloud rather than being dropped.  So, if it could be dropped that would be great.

**Comment by greghesp** [comment]
Shouldn't be too hard to fix.  I've pushed it to the source code, but won't add it to a release just yet.

If you want to add it into your existing install, just overwrite this file with the content here: https://github.com/greghesp/assistant-relay/blob/v3/relay/routes/index.js

**Comment by ryancasler** [comment]
Okay....I will try that out later today.

BTW, Docker is updates for v3.0.4.

**Comment by greghesp** [comment]
Added to V3.0.5
