### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by niekvlessert** [greghesp/assistant-relay#128]
Maybe I'm causing this issue myself but I have a network error when accessing the webgui for the first time. Just followed the instructions, download a relase.zip, npm install, npm run start. Nothing special. Then when visiting the webinterface it says network error, that's it, no wizard. The raspberry Pi 3b I'm running this one has internet, as well as my mac. Tried different browsers. Any tips?

Running on Raspberry Pi 3b with Raspbian 10 and nodejs 13.1.0.

**Comment by niekvlessert** [comment]
I now discovered the console gives connection error to 127.0.0.1. So I did a ssh -L 3000:localhost:3000 <ip> and not it works..

**Comment by srvrguy** [comment]
If you get the page that says "Whoops! We lost your server connection" you can enter in the IP of the remote system and that will solve the issue. This information is saved in local storage in the browser, so you will need to do that again if you connect from a different browser or different computer.

**Comment by niekvlessert** [comment]
I'm not aware of that message & option. I just see the google speaker speaking animation with network error in the top, no options afaik.

**Comment by 808Boss** [comment]
i'm receiving the same error message. What can i do? I included a sceenshot. 
<img width="1677" alt="Schermafbeelding 2019-11-19 om 19 05 47" src="https://user-images.githubusercontent.com/45951839/69173671-88212300-0b00-11ea-83ee-783289af473e.png">

**Comment by Mallinanga** [comment]
Same here

**Comment by ryancasler** [comment]
You should try with node v10.  That's the version that was used for development.

**Comment by niekvlessert** [comment]
Well, as I said you could make an ssh tunnel to get it working. It's a work around and I just noticed that's still needed. When having that it works fine with the new node version... should be doable to fix. On the same subnet.
`ssh -L 3000:localhost:3000 <user>@<server ip>`

**Comment by niekvlessert** [comment]
I've been trying to debug it, I can't get it work since my knowledge of how this works is too limited, my changes to js files are simply being ignored for some reason.  Usercount is the first one that goes wrong; probably this in routes/server.js;
`router.post('/userCount',async(req, res) => {`

But as I said, changes to those files are ignored...

**Comment by niekvlessert** [comment]
It's a webpack thing. Since @greghesp tells us to download the release instead of the sources I'm not sure how he generates the webpack files. Any tips on that?

**Comment by greghesp** [comment]
The UI is build using CRA. If you've downloaded the source code, you can build the UI using npm run build, or hotload it for development using npm run start.

As for the server in development, you can run that for development using npm run dev.

I'll have a look tomorrow to see if I can debug this. I've not had this error myself but might be because I'm developing in the same system it's running in

**Comment by niekvlessert** [comment]
The source does not include a package.json, where to get that? I might better wait for you...

**Comment by greghesp** [comment]
@niekvlessert  it should do. It's in the repo: https://github.com/greghesp/assistant-relay/blob/v3/client/package.json

**Comment by niekvlessert** [comment]
Right, I wasn't looking in subdirectories... ;P

**Comment by greghesp** [comment]
Ah yes. The server runs Express, and the Client is React. To build the release, I have to move the built client files into the express server to host it. Hopefully that makes sense

**Comment by niekvlessert** [comment]
Sure. :) I tried the source code, but my Raspberry Pi is not really up to the task, I'm willing to install a VM to test it more if needed, but it's not very hard to reproduce the issue; just start the release.zip version somewhere and visit it from another host.

**Comment by greghesp** [comment]
Ah found the bug.  My fault, commented some stuff out when testing by mistake.  Will fix shortly

**Comment by greghesp** [comment]
Fixed: https://github.com/greghesp/assistant-relay/releases/tag/v3.0.5

**Comment by niekvlessert** [comment]
I realised I didn't thank you; so thanks for fixing this. :)

**Comment by am9magic** [comment]
I am getting a client error, can someone help me on what is causing it.

![image](https://user-images.githubusercontent.com/73008266/96339064-1af37600-1060-11eb-8248-405d902efd19.png)
