### ISSUE TITLE
Localhost works, remote doesn't

### ISSUE THREAD

**Issue by viennaotf** [greghesp/assistant-relay#129]
**Describe the bug**
Setting up the relay for localhost works as promised, broadcasting works if i would do: 
```
{
    "user": "test",
    "command": "yo",
    "broadcast": true
}
```
But if I were to do the exact same thing on a web server that runs the app just fine, I get no errors but instead nothing is happening to my device. I've already tried this out by verifying the domain that it belongs to me, it's all the same version as well and I get no warnings/errors. I get the toast that allows me to playback the audio response and that's working just fine, just the actual broadcasting doesn't seem to work. With both the same code, client secret, user names and the same commands only localhost seems to actually push the broadcast to my speaker

**To Reproduce**
1. Install the relay on your own pc, follow the instructions given and try a simple broadcast command
2. Do the exact same thing but on a webserver instead

**Expected behavior**
My google home speakers receiving the broadcast "test" when called from a webserver

**Screenshots**
This is on the webserver: https://gyazo.com/ff08563784cb5363b3c8e07dd559d995
This is on localhost: https://gyazo.com/cc51545cc168de870e165d4e40e3dd17

**Desktop (please complete the following information):**
-  Windows 10
 - Opera
 - Version 64.0.3417.92

**Additional context**
No errors in consoles/logs etc

**Comment by ryancasler** [comment]
> But if I were to do the exact same thing on a web server that runs the app just fine, I get no errors but instead nothing is happening to my device.

Do you mean that GAR is running on the cloud or something?  Google Assistant Relay must be running on your local network in order for the Broadcast to work.  That's how it's able to send the message to your speakers.  This is a limitation of the Google Assistant SDK.  While you are able to broadcast to all the devices on your account if you do a Broadcast from your phone, the same functionality is not available to the SDK.  This is a security measure that Google put in place a while ago.

**Comment by greghesp** [comment]
@ryancasler  is correct, the device running AR **must** be on your local network.
Google locked the SDK down a while ago (around the same time they forced the "incoming broadcast from...") due to security concerns.
