### ISSUE TITLE
Smartthing app cannot  save the device

### ISSUE THREAD

**Issue by naseemr** [greghesp/assistant-relay#13]
Hi Iam getting error when I try to save the device.  I get error "deviceNetworkId must be unique"

**Comment by zbuh** [comment]
same here...

**Comment by naseemr** [comment]
Figured out what is the cause. if you have another smarting device using the same IP then it will not let you save.

**Comment by greghesp** [comment]
If you go into the ID, change the deviceNetworkId.  You've probably got another custom device with the same ID
