### ISSUE TITLE
100% failure rate in Google console

### ISSUE THREAD

**Issue by Webunity** [greghesp/assistant-relay#130]
Although the assistant relay seems to be working just fine, i get a 100% failure rate in my google console. Don't know if it is caused by the software maybe not returning the correct codes to Google?

![Screenshot 2019-11-22 at 08 13 04](https://user-images.githubusercontent.com/186093/69405495-20d1c180-0d00-11ea-9e99-c07818185a3b.png)

**Comment by greghesp** [comment]
Where are you seeing this?  Could you link it please?

**Comment by ryancasler** [comment]
It has always returned 100% failure rate even though it works fine.

**Comment by greghesp** [comment]
I believe this is an error in the Google console.
