### ISSUE TITLE
No Response Collected From Google Home

### ISSUE THREAD

**Issue by chasen-bettinger** [greghesp/assistant-relay#131]
**Describe the bug**
I am using the sandbox to send broadcasts and converse with the google home. 

Here's what I'm sending:

![image](https://user-images.githubusercontent.com/24480592/69487753-903cd380-0e1c-11ea-8559-a207209df0cb.png)

The message is sent through my Google Home successfully. Once submitted, the network responds almost immediately and informing me that I have given no response.

Here's the payload:

```
{
  "response": "",
  "audio": "http://10.0.0.15:3000/server/audio?v=1574557870549",
  "success": true
}
```

I was reading here: https://support.google.com/googlenest/answer/7531913 that you can only reply to broadcasts after they've been completed. I haven't been given an opportunity to reply when the network responds on the client, no wonder there is no response.

Then, I say `Ok Google, send a reply` and reply with a message. Google informs me that I've successfully replied to the message. I go to to Home, thinking that my reply would've been updated. Nope. Here is the payload I'm seeing on Home:

```
[
  {
    "command": "broadcast the movie is about to start",
    "response": "",
    "timestamp": 1574556324403
  },
  {
    "command": "broadcast the movie is about to start",
    "response": "",
    "timestamp": 1574556071405
  },
  {
    "command": "broadcast i'm home",
    "response": "",
    "timestamp": 1574556016768
  },
  {
    "command": "broadcast i'm home",
    "response": "",
    "timestamp": 1574555975027
  },
  {
    "command": "broadcast i'm home",
    "response": "",
    "timestamp": 1574555951921
  }
]
```

**Expected behavior**
I expected the network request to remain pending until a response had been recorded and/or that after sending a response, the client would recognize that I've responded to the broadcast at some later point in time.

**Desktop (please complete the following information):**
-  Platform: Ubuntu 18.04
 - Browser: Chrome
 - Version: 3.0.5

**Additional context**
- I have validated that my phone is attached to the Google Home Mini by using the google assistant feature on my Pixel to broadcast a message to the Google Home.
- I have validated that IPV6 on my router is disabled
- I have validated that the computer I am using and the Google Home Mini are on the same network

Nevertheless, thank you for putting in time and making such an awesome library. This is incredible!

**Comment by ryancasler** [comment]
> I expected the network request to remain pending until a response had been recorded and/or that after sending a response, the client would recognize that I've responded to the broadcast at some later point in time.

That is incorrect.  Google Assistant Relay does not support replies to broadcasts to perform any action.  It simply performs the broadcast.  What were you expecting it to do with the response?

**Comment by greghesp** [comment]
Converse takes the text response from Assistant, and broadcasts that back to your Google Homes.

If you ask how tall brad pitt is with the converse parameter set, it will broadcast his height.

Hope that makes sense
