### ISSUE TITLE
Broadcasts not playing on Google Homes

### ISSUE THREAD

**Issue by Jay2645** [greghesp/assistant-relay#132]
**Describe the bug**

When using the sandbox, I can issue commands like "turn on the lights" and they work as expected, but using the broadcast features gives a "command successful" with a link to hear some audio output... but the actual broadcast doesn't play out of any of my Google Home Minis.

If I click on the "command successful" link to hear the audio, it's the assistant saying "Okay, broadcasting now." If I used a preset, the audio changes to "Okay, broadcasting now" followed by the audio it was supposed to broadcast to the Homes.

For example, if I use the "on my way" preset, nothing will happen on the speakers at all. However, the sandbox will report that the broadcast was successful and give me a link to an audio file saying, "Okay, broadcasting now. Hey there! Jay2645 is on the way!"

**To Reproduce**

1. Open Assistant Relay on a web browser, going to http://192.x.x.x:3000.

2. Open the "sandbox" mode

3. Try to broadcast some audio, or try to use a preset.

**Expected behavior**

Audio will come out of the Google Homes.

**Actual behavior**

I get a link to a voice file of the Google Assistant saying "broadcasting now," but nothing happens on the Google Homes.

**Desktop (please complete the following information):**

* Platform: Raspberry Pi v3, running Hass.io. [Assistant Relay is running inside of a container managed by this Hass.io addon.](https://github.com/Apipa169/Assistant-Relay-for-Hassio) Since I know this is a non-standard setup, I also tried a manually installing it on a NAS running Debian Jessie, but I had the same problem.

* Browser: Chromium Edge, beta branch

* Release v3.0.5

**Additional context**

Unlike issue #129, I can't even get localhost to work. Here's the output from my NAS when I was trying it there:

`root@Nile-Nellie:~# curl -X POST -d '{"command":"hello world", "user":"jay", "broadcast":true, "converse":true}' -H 'Content-Type: application/json; charset=utf-8' 127.0.0.1:3000/assistant`

`{"response":"","audio":"http://192.168.86.222:3000/server/audio?v=1575025337513","success":true}`

As mentioned, I am able to do things like control the lights just fine. I've tried every possible combination of "broadcast" and "converse" to no avail.

My Pi and NAS are running on the same local network as all my Homes. Both the Pi and the NAS are directly hooked up via switch into a Google OnHub router, whereas the Homes are obviously all on Wi-Fi.

---

Here are the logs from the container:

```
                        -------------
__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__
                          Runtime Edition
        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.
                Start and Daemonize any application:
                $ pm2 start app.js
                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4
                Monitor in production:
                $ pm2 monitor
                Make pm2 auto-boot at server restart:
                $ pm2 startup
                To go further checkout:
                http://pm2.io/
                        -------------
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /assistant_relay/bin/www in fork_mode (1 instance)
[PM2] Done.
┌─────┬──────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ www  │ default     │ 0.0.0   │ fork    │ 51       │ 0s     │ 0    │ online    │ 0%       │ 21.6mb   │ root     │ disabled │
└─────┴──────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[TAILING] Tailing last 15 lines for [www] process (change the value with --lines option)
/root/.pm2/logs/www-out.log last 15 lines:
/root/.pm2/logs/www-error.log last 15 lines:
0|www  | Assistant Relay Server Initialized
0|www  | Visit http://172.30.33.3:3000 in a browser to configure
0|www  | GET / 304 16.627 ms - -
0|www  | GET /static/css/2.3a86971d.chunk.css 304 8.036 ms - -
0|www  | GET /static/js/main.a3431f03.chunk.js 304 7.344 ms - -
0|www  | GET /static/js/2.1e09be87.chunk.js 304 4.204 ms - -
0|www  | OPTIONS /server/userCount 204 4.366 ms - 0
0|www  | GET /favicon-32x32.png 200 10.826 ms - 1435
0|www  | POST /server/userCount 200 90.800 ms - 10
0|www  | OPTIONS /server/addUser 204 0.990 ms - 0
0|www  | POST /server/addUser 200 1932.740 ms - 297
0|www  | OPTIONS /server/processOAuth 204 0.896 ms - 0
0|www  | POST /server/processOAuth 200 554.886 ms - -
0|www  | OPTIONS /server/userCount 204 0.480 ms - 0
0|www  | POST /server/userCount 200 41.255 ms - 10
0|www  | OPTIONS /server/getResponses 204 0.498 ms - 0
0|www  | POST /server/getResponses 200 51.793 ms - 16
0|www  | OPTIONS /server/getConfig 204 0.456 ms - 0
0|www  | POST /server/getConfig 200 42.385 ms - 126
0|www  | OPTIONS /assistant 204 1.128 ms - 0
0|www  | Conversation Complete
0|www  | POST /assistant 200 2222.775 ms - 93
0|www  | Conversation Complete
0|www  | POST /assistant 200 2152.105 ms - 93
0|www  | OPTIONS /server/getResponses 204 1.052 ms - 0
0|www  | POST /server/getResponses 200 1164.830 ms - 176
0|www  | GET / 200 5.242 ms - 3159
0|www  | GET /home 304 10.289 ms - -
0|www  | GET /static/css/2.3a86971d.chunk.css 304 2.833 ms - -
0|www  | GET /static/js/main.a3431f03.chunk.js 304 5.867 ms - -
0|www  | GET /static/js/2.1e09be87.chunk.js 304 4.645 ms - -
0|www  | OPTIONS /server/userCount 204 0.816 ms - 0
0|www  | POST /server/userCount 200 38.168 ms - 10
0|www  | GET /favicon-32x32.png 200 52.350 ms - 1435
0|www  | OPTIONS /server/getResponses 204 0.903 ms - 0
0|www  | POST /server/getResponses 200 46.762 ms - 176
0|www  | OPTIONS /server/getConfig 204 0.926 ms - 0
0|www  | POST /server/getConfig 200 43.903 ms - 126
0|www  | OPTIONS /assistant 204 0.968 ms - 0
0|www  | Conversation Complete
0|www  | POST /assistant 200 2759.059 ms - 93
0|www  | OPTIONS /assistant 204 0.766 ms - 0
0|www  | Conversation Complete
0|www  | POST /assistant 200 2207.320 ms - 93
0|www  | OPTIONS /assistant 204 0.769 ms - 0
0|www  | Conversation Complete
0|www  | POST /assistant 200 2536.401 ms - 93
0|www  | OPTIONS /assistant 204 0.777 ms - 0
0|www  | Conversation Complete
0|www  | POST /assistant 200 2637.597 ms - 93
```

Note that as per the readme of the Hass.io plugin, the IP address listed in the logs is just the address of the container and not the actual address of the server. I don't know where the logs live in the NPM-based install, but I can get them to you if needed.

My public IP is IPv6. Not sure if that affects anything.

I know this is a tricky one to figure out without access to the actual hardware, so let me know if there's anything else I can do to help you debug, or if I just have things set up incorrectly.

**Comment by Jay2645** [comment]
Update: Changing my public IP to IPv4 fixed the issue. Might be worth adding something to the readme? Either way, going to go ahead and mark this as closed.

**Comment by rlowens** [comment]
> Update: Changing my public IP to IPv4 fixed the issue. 

Mind giving more information on how you did that? I'm running Google Fiber and that router doesn't seem to have any settings for disabling IPv6 as far as I can see.

You only changed your public WAN IP from IPv6 to IPv4? Were you getting IPv6 addresses internally on your LAN? Are you still?

I'm confused what exactly you changed to get it working.

I'm running this in hassio as well.

**Comment by Jay2645** [comment]
@rlowens I'm using a Google OnHub router with AT&T as my ISP. The OnHub gives me access to the Google Wi-Fi app; I believe you can get access to the app using Google's mesh routers as well. I'm not sure if Google Fiber uses the same app or the same router.

In the app, I go to Settings -> Network & General ->Advanced Networking -> IPv6. This gives me a setting to toggle my public WAN between IPv4 and IPv6 -- I originally had it set to IPv6, and changing that to IPv4 solved the issue. You'd figure since we're only working with Google products everything would play nice together, but this *is* Google we're talking about.

My LAN has always been IPv4 -- as far as I can tell, there's no way in the limited settings Google Wi-Fi gives me to enable IPv6 for LAN, just WAN.

I didn't need to touch anything in Hassio at all, other than just installing the addon.

**Comment by rlowens** [comment]
Thanks for the info. No, Google Fiber with a Network Box doesn't have an option to disable IPv6. https://support.google.com/fiber/thread/2012111?hl=en

I'd have to replace the Network Box with a Google WiFi or a real router (Ubiquiti, etc.). Not worth it just for playing with Assistant Relay.

**Comment by ryancasler** [comment]
The IPv6 bug is a bug with the Google Assistant SDK that I found a couple of years ago now.  Google has acknowledged it but also made no attempt to fix it.  So, there really is nothing that can be done within GAR to get it to work unfortunately.  Sorry there's not better news.
