### ISSUE TITLE
More languages?

### ISSUE THREAD

**Issue by olskar** [greghesp/assistant-relay#133]
**Is your feature request related to a problem? Please describe.**
I earlier used https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music/37274 to broadcast but it has stopped working. It did broadcast in the language I have choosen for my google homes, swedish.

Isnt it possible to add swedish for this?
It seems to be possible according to https://developers.google.com/assistant/console/languages-locales 

where sv-SE is listed

**Comment by Apipa169** [comment]
Only the languages in the link below are supported by the Google SDK, so by Assistant Relay.

https://developers.google.com/assistant/sdk/reference/rpc/languages

In my case there is no support for Dutch, but I’m still able to send broadcasts in Dutch. Only the prefix “broadcast from xxx” is in English.

**Comment by olskar** [comment]
I see, thanks, closing this then :)
