### ISSUE TITLE
Not a valid IP Address

### ISSUE THREAD

**Issue by mlakerveld** [greghesp/assistant-relay#134]
**Describe the bug**
I run a docker image running Assistant Relay on my NAS. I have  modified the port via docker from 3000 to 3001. I go to the webinterface, and it keeps telling me it cant connect ("Whoops! We lost your server connection").
It asks if I want to enter its address and port. I fill in 3001, and I see it POSTing to 3001 on 127.0.0.1. But I can't change the IP Address, it keeps saying its not a valid ipaddress. 
127.0.0.1 : Invalid
192.168.1.10 : Invalid

**To Reproduce**
1. Go to the URL for the webinterface.
2. It says "Whoops! We lost your server connection"
3. Try and fill in an IP Address

**Expected behavior**
I expect it to accept the IP Address I fill in.

**Screenshots**
![image](https://user-images.githubusercontent.com/1911588/69901196-f7a7d580-137e-11ea-91bf-fce8d083546a.png)

**Desktop (please complete the following information):**
-  Synology NAS running Docker
 - All
 - branch v3

**Comment by mlakerveld** [comment]
I'm starting to think this is because Im running it in a docker container.
But its still weird that it doesnt validate the IP addresses correctly

**Comment by Apipa169** [comment]
> I'm starting to think this is because Im running it in a docker container.
> But its still weird that it doesnt validate the IP addresses correctly

I have AR running in a container too. When I change to host port to 3001 like you did I'm not having this issue.

**Comment by ryancasler** [comment]
I have GAR running in Docker.  What type of network are you using for GAR?  A bridge?  If so, the IP you have to enter there will be the IP address of your server.  Are you exposing the port in your docker run command?  Some details about how you are setting up docker to run would be helpful.

**Comment by mlakerveld** [comment]
So im managing my Docker instances with the Synology software.
It is running bridged with port 3001 passing to 3001.
I also put port: 3001 in the config.json file.

![image](https://user-images.githubusercontent.com/1911588/69905919-496e5100-13bb-11ea-8233-1ca3ecd222ba.png)
![image](https://user-images.githubusercontent.com/1911588/69905916-43787000-13bb-11ea-81ab-d56181bc2268.png)
![image](https://user-images.githubusercontent.com/1911588/69905922-4ecb9b80-13bb-11ea-83a7-dfcce360be3e.png)
![image](https://user-images.githubusercontent.com/1911588/69905923-52f7b900-13bb-11ea-9931-df6466f1363c.png)

**Comment by mlakerveld** [comment]
But I'm getting the "Not a valid IP Address" notification. Looking at the code it only checks is_ip with the npm package with the same name. So I'm not sure why its failing.

**Comment by ryancasler** [comment]
You should not modify the port 3000 inside the container.  Instead you should map post 3000 to port 3001.  Then use the IP address of your server and port 3001 when you access the server.  So, the local port would be 3001 and the container port would be 3000.  I'm also not sure why you are exposing any volumes from inside the container as that is not necessary for GAR to function correctly and will not provide extra functionality.

**Comment by greghesp** [comment]
I think @mlakerveld bug is more to do with the is_ip package not validating his IP address correctly, which is a bit odd.

I've just tested this with that IP address using my instance and it validates the IP address fine.  I'd imagine maybe theres something in Docker causing an issue with the module maybe?

As a workaround, right click on the window, hit inspect.  Go to application, local storage and change the values to your IP and port like below.

![image](https://user-images.githubusercontent.com/768908/69962462-f654e500-1505-11ea-9f70-1024f7d20a7c.png)

**Comment by greghesp** [comment]
@mlakerveld I suggest you download the latest version 3.1.0.  I've removed the need for this
