### ISSUE TITLE
Clearing time with quiet mode enabled disables quiet mode forever

### ISSUE THREAD

**Issue by Jay2645** [greghesp/assistant-relay#135]
**Describe the bug**

If you go into quiet mode, set a time, then hit the little "x" in the dialog box to clear said time, it changes the text to read "Invalid date." No matter what you do, you're not able to change this to any other value -- the text will always read "Invalid date" and quiet mode won't work.

**To Reproduce**

1. Enable quiet mode.

2. Set some hours for start and finish

3. Hit the "x" button in the right corner of the input box to try to clear the input

**Expected behavior**

Input gets cleared, allowing you to input a new time

**Screenshots**

![image](https://user-images.githubusercontent.com/2058763/69911906-189c1500-13d7-11ea-9161-0fe7cd0ea291.png)

**Desktop (please complete the following information):**

- Platform:  Windows 10

- Browser: Chromium Edge Beta

- Version: Release v3.0.5

**Comment by ryancasler** [comment]
Have you tried toggling Quiet mode off and then on again?

**Comment by Jay2645** [comment]
@ryancasler Yeah, I tried that. The "Invalid date" stays cached, even if Quiet Mode is turned off and the system is restarted.

**Comment by greghesp** [comment]
Fixed: https://github.com/greghesp/assistant-relay/releases/tag/v3.0.6
