### ISSUE TITLE
Opens blank tab after uploading credentials

### ISSUE THREAD

**Issue by tylergets** [greghesp/assistant-relay#138]
After uploading my JSON credentials, the app opens a blank tab and then asks for an authentication code. I am unable to proceed from here

**Comment by schwarzenbergf** [comment]
Same here. Which Auth-Code to use?

**Comment by Apipa169** [comment]
I had a similar issue the first time I set it up. Disabling the pop-up blocker and try it again did the trick for me.

**Comment by greghesp** [comment]
You might have to configure your oauth consent screen in the console, however it seems a little odd that Google would make it blank if not configured.

Can you check what @Apipa169 suggested? It's not anything on my side that it loads as it's going to Google for authentication

**Comment by schwarzenbergf** [comment]
pop-up blocker is not enabled. I cleared the cache, reinstalled the assistant relay, created a new project (Google), I had already one which I tried to use first. Created new credential set. Does not help.
One question: which User name should I use for the downloaded credential set? Is this my choice?
I use Chromium on Ubuntu. I will try this now with Chrome on Windows.

**Comment by Apipa169** [comment]
Username can be anything you like, you have to use this name when you send a command to AR.

How do you run Assistant Relay?

**Comment by schwarzenbergf** [comment]
I run it as add-on in Hass.io. Home Assistant is latest version.
I had to use another port (3000 is used by Grafana), but in the meanwhile I
also tried with the default port (stopped Grafana).
No difference.
Thanks.
==============================
Dr. Frank Schwarzenberg
Jeerschtekamp 6
47809 Krefeld
+49(2151)540880
+491782347809
=============================


Am Do., 5. Dez. 2019 um 11:35 Uhr schrieb Apipa169 <notifications@github.com

**Comment by schwarzenbergf** [comment]
I tried this on Windows with Chrome. Same result. In the Log I find this:

0|www  | Assistant Relay Server Initialized
0|www  | Visit http://172.30.33.2:3000 in a browser to configure
0|www  | GET / 200 10.515 ms - 3197
0|www  | GET /static/js/main.39511409.chunk.js 200 1.346 ms - 60851
0|www  | GET /static/css/2.08a37119.chunk.css 200 4.497 ms - 259521
0|www  | GET /static/js/2.97d629b7.chunk.js 200 3.416 ms - 1755637
0|www  | POST /server/userCount 200 35.787 ms - 10
0|www  | GET /favicon-32x32.png 200 1.856 ms - 1435
0|www  | TypeError: Cannot read property 'installed' of undefined
0|www  |     at exports.auth (/assistant_relay/helpers/auth.js:10:29)
0|www  |     at /assistant_relay/routes/server.js:41:23
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  | POST /server/addUser 200 10.184 ms - 2

Any idea what could be wrong ? ('Cannot read property 'installed' of undefined')

**Comment by Apipa169** [comment]
Might be an issue with the addon. I have to investigate that, I’ll come back to you.

(I advise you to edit your comment, your address and phone number is in it)

**Comment by schwarzenbergf** [comment]
Thank you!

**Comment by sfanicola** [comment]
I add myself ... Same conditions.. same blank page.

**Comment by gjhilli** [comment]
> Same here. Which Auth-Code to use?

As per instructions ...
"Follow this guide and come back once Step 5 is complete"

Step 4 of this guide :
"Keep this browser tab open. You will use it to register a device model in a later step".

When you subsequently select the "Register Model" button it is the code that is generated by this step that is to be used as the Auth-Code.

**Comment by greghesp** [comment]
The auth code to use is the one from the popup. It will ask you to authenticate your Google Account with the project your just made. Once you give it permission, it'll give you an auth code to paste back into AR

**Comment by Apipa169** [comment]
I have made a rollback to the previous release. This fixed the problem for me.

The add-on is now using AR v3.0.6 instead of v3.1.0.

I am working on a new release without this bug. It need some investigation where it came from.

**Comment by tylergets** [comment]
My original issue is unrelated to hass.io, i was simply running the project from the release zip.

I will attempt a rollback later this evening

**Comment by greghesp** [comment]
Don't rollback, looks like Google changed the auth method and broke the integration..

**Comment by greghesp** [comment]
Can you update to v3.1.2: https://github.com/greghesp/assistant-relay/releases/tag/v.3.1.2

I'm not sure what happened, it looks like a middleware component for Express updated and changed how it read data.  It's the same issue that prevent the commands from working

**Comment by Apipa169** [comment]
Thanks for the quick fix!

I have updated the Hass.io add-on to AR v3.1.2, this works fine now!
