### ISSUE TITLE
broadcast variable value

### ISSUE THREAD

**Issue by naseemr** [greghesp/assistant-relay#14]
Hi, I am trying to broadcast BEDROOM's thermostats setpoint. But it is not broadcasting, what I am doing wrong? can someone help me?
![image](https://user-images.githubusercontent.com/3306597/36346860-e50cf882-140d-11e8-9621-54bbdbba4daf.png)

**Comment by greghesp** [comment]
What message is showing in the console?

**Comment by naseemr** [comment]
thanks for your response. here is my logs:

+1ms | ╔Received event [BEDROOM].coolingSetpoint = 72 with a delay of 50ms
-- | --
+72ms | ║RunTime Analysis CS > 13ms > PS > 42ms > PE > 17ms > CE
+74ms | ║Runtime (37075 bytes) successfully initialized in 42ms (v0.3.104.20180323) (72ms)
+75ms | ║╔Execution stage started
+84ms | ║║Comparison (decimal) 72.0 changes = true (1ms)
+85ms | ║║Cancelling condition #4's schedules...
+86ms | ║║Condition #4 evaluated true (5ms)
+87ms | ║║Cancelling condition #1's schedules...
+88ms | ║║Condition group #1 evaluated true (state changed) (7ms)
+90ms | ║║Cancelling statement #2's schedules...
+191ms | ║║Executed physical command [Google Assistant Relay].broadcast([72.0]) (91ms)
+192ms | ║║Executed [Google Assistant Relay].broadcast (93ms)
+195ms | ║╚Execution stage complete. (120ms)
+197ms | ╚Event processed successfully (196ms)

**Comment by greghesp** [comment]
Are there any logs from the console of the relay?

**Comment by naseemr** [comment]
Where would I look for the log files?

**Comment by kevintee23** [comment]
Here's a piston that will announce the variable. Plus, from the snapshot, you were using the wrong command. It should be customCommand rather than broadcast.

![example01](https://user-images.githubusercontent.com/31426495/38281723-668fdafa-37ef-11e8-8e1b-d851ca8336c4.png)
