### ISSUE TITLE
Media Controls? 

### ISSUE THREAD

**Issue by sfanicola** [greghesp/assistant-relay#140]
Will there ever be a way to send a media control for videos on chromecast? I'm desperately searching just a way to skip to next YouTube video ...
Are there SDK limitations? 
Would there be a way to bypass them?

**Comment by ryancasler** [comment]
They are SDK limitations.  
It's not like the functionality is there and turned off.  The functionality doesn't exist.  So, there's nothing anyone can do.   

Is your chromecast connected to a TV with CEC capability?  have you tried using "next track" or "fast forward" on your remote for the TV your chromecast is connected to.   I know play/pause and stop work but I've never tried next track or fast forward.  Worth a shot.

**Comment by greghesp** [comment]
As Ryan said, this is an SDK limitation
