### ISSUE TITLE
Network Error on step 3 submit token

### ISSUE THREAD

**Issue by Tsaaek** [greghesp/assistant-relay#141]
I can't get past the last step in the setup. 

The error i get:

> 0|www  | node /home/pi/assistant-relay/bin/www: symbol lookup error: /home/pi/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8

Any suggestions on how to fix this?

**Comment by greghesp** [comment]
Can you try v3.1.3 please
https://github.com/greghesp/assistant-relay/releases/tag/v3.1.3
