### ISSUE TITLE
Unable to delete a user

### ISSUE THREAD

**Issue by theRealMCQwerty** [greghesp/assistant-relay#142]
**Describe the bug**
Unable to delete a user that was previously added.

**To Reproduce**
1. In the initial setup, add a username and upload a secrets file
2. Close the browser before entering an auth code (because I was signed into the wrong google account)
3. Open the dashboard 
4. Click 'Add New User
5. Enter the same user name and upload secrets file - "username already exists' error
6. **How do I delete a previously created user??**

**Expected behavior**
Should be a tab in the dashboard listing all users with a delete button in order to delete a given user

**Screenshots**
![image](https://user-images.githubusercontent.com/26889036/70755628-f754f600-1cff-11ea-85ee-e1270ecfbaf1.png)

**Desktop (please complete the following information):**
-  Platform [Windows]
 - Browser [chrome]
 - Version [latest]

**Comment by greghesp** [comment]
If you go into bin/config.json, there will be an array called "users" like so:

```
"users": [
    {
      "name": "greg",
      "secret": {
        "installed": {
          "client_id": "123",
          "project_id": "gar-demo",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_secret": "123",
          "redirect_uris": [
            "urn:ietf:wg:oauth:2.0:oob",
            "http://localhost"
          ]
        }
      },
      "tokens": {
        "access_token": "123",
        "refresh_token": "123",
        "scope": "https://www.googleapis.com/auth/assistant-sdk-prototype",
        "token_type": "Bearer",
        "expiry_date": 1575737437056
      }
    }
  ]
```

You can delete each user by deleting their user object. Ie, if I wanted to remove greg, the above would simply become

`users: []`

I will add this into the UI at some point

**Comment by greghesp** [comment]
Added in V3.2
