### ISSUE TITLE
The documentation should clearly indicate where the configuration is stored.

### ISSUE THREAD

**Issue by lddubeau** [greghesp/assistant-relay#143]
**Describe the bug**
It is not clear where the configuration of version 3 is stored.

**To Reproduce**
I searched the documentation (and the issues), but could not find any mention of how and where the configuration is stored.

**Expected behavior**
A clear description in the documentation of where the configuration is stored.

This information is important for those who want to back up the configuration, or who run assistant-relay in a Docker container and want the configuration to persist. 

I'm guessing that `bin/config.json` is *a* configuration file, but is it the *only* configuration file?

**Comment by Apipa169** [comment]
bin/config.json is the only file where all configuration is stored. In bin/audio-responses you can find the audio responses from Google, I recommend to keep this in a volume as well when you are using docker.

**Comment by 10-v** [comment]
...
