### ISSUE TITLE
Get response text back from a request?

### ISSUE THREAD

**Issue by madcock** [greghesp/assistant-relay#144]
While the audio response is saved, and a link is provided, could the assistant-relay provide the response text? It seems there is a value returned called "response", but it's always empty.

I'd like to be able to parse and act on the response in my own code, when calling through to the assistant-relay, but I don't see a practical way to do that now, without the response as text. Thanks!

**Comment by greghesp** [comment]
This depends on what you ask it, and if Google returns a text value or not. 
Some responses will give you the text, for instance ask it the time.
