### ISSUE TITLE
"User" is not broadcasted correctly

### ISSUE THREAD

**Issue by technogizmo007** [greghesp/assistant-relay#147]
**Describe the bug**
Playing in the sandbox to send a broadcast, I had already added another user successfully, but when I fill in the "user" box with that new user and then broadcast, the broadcast does not say the correct user's name- instead it states the original username I used to setup everything.

**To Reproduce**
After successfully creating a new user under "Add New User" tab, open Sandbox.
Enter that new user's name in the User: box.
Enter anything you want to broadcast in Command:.
Check Yes to Broadcast
Submit
Broadcasts successfully on devices, however, GA will state "New broadcast from [original username that setup account]." and not the user that was just put into User:.

**Expected behavior**
GA will broadcast the user's name that is input in User: field.

**Additional context**
I setup Assistant Relay with the user "Doc". Everything worked great: I would get GA to broadcast "Broadcast from Doc: (context here)." I added a new user named "system", successful. Through Sandbox, I input User: system; Command: (testing context here); Broadcast Yes; submitted. The broadcast says "Broadcast from Doc (not "system"): (testing context here)."

**Comment by ryancasler** [comment]
Did you set it up using the same JSON file from Google?  That's where the Assistant gets your name.  The name set inside Assistant Relay is only used for the commands to Relay.  Not the name that will be broadcast.  The only way to get a different name to broadcast is to set up another google account, link it to your mini, create the Console project, download the json file....then use that to set up the new user in Relay.  I've done this before and it does work.

**Comment by technogizmo007** [comment]
@ryancasler Yes, all setup with same account, which I would assume means the same JSON file. All I did was create a new user from within the AR web interface and uploaded the same secret file to that new user. Now if I only ever want it to say "System" instead of my name, can I somehow just edit the JSON file that has my name from Google in it or is that a solid connection to Google? Would another possible alternative be starting fresh but before I setup, set my Google account name to "System", setup AR, then change it back to my name?

**Comment by ryancasler** [comment]
No.  You cannot change the name that Google Home will use when it creates a broadcast unless you change the name within your Google Account, for all the reasons I have already explained.  Everything with GAR is only used for GAR.  The "broadcast from" message is generated by Google Assistant.  It knows what account to use based on the JSON file you upload which you cannot modify once it has been downloaded.  The only choice if you want a different name broadcast there is to create another google account.

**Comment by technogizmo007** [comment]
Thanks for your insight on this, @ryancasler . I will close this out and won't put it in feature request because of it being on the Google side, while this works wonderfully.
