### ISSUE TITLE
Play button always use 127.0.0.1 as host.

### ISSUE THREAD

**Issue by michaelarnauts** [greghesp/assistant-relay#148]
**Describe the bug**
The play button always seems to use 127.0.0.1 as a host.

Maybe the `await` is missing here? https://github.com/greghesp/assistant-relay/blob/v3/client/src/components/PlayButton/index.js#L18

I'm running the application in Home Assistant with https://github.com/Apipa169/Assistant-Relay-for-Hassio

**To Reproduce**
1. Make a request
2. Click the play button.
3. A request is made to 127.0.0.1, but that doesn't work.

**Expected behavior**
Use the hostname that is used to load the interface. Maybe by omitting the host and port, but just the path and just having the browser figure it out? 

**Desktop (please complete the following information):**
-  Platform: Hass.IO
 - Browser: Chrome
 - Version: 3.1.3

**Comment by michaelarnauts** [comment]
Might be related to #134, but it is not fixed in the latest release.

**Comment by ryancasler** [comment]
> 2\. Click the play button.

What play button?

**Comment by michaelarnauts** [comment]
I mean the play button on the dashboard or popup to play an audio response.

**Comment by michaelarnauts** [comment]
Setting the ip var in local settings fixes it, but this should not be necessary.

**Comment by ryancasler** [comment]
Do you mean the Submit button?  
![image](https://user-images.githubusercontent.com/30270489/71773009-6dc1ce00-2f23-11ea-9ea6-23daaca40be0.png)

If that's not the dashboard you're talking about, then you need to show a screenshot or something.  Or do you mean the play button next to the returned response?

**Comment by michaelarnauts** [comment]
I mean that play button indeed, to play the audio file of a response. The code uses 127.0.0.1 by default if no ip is available (see URL to the PlayButton component from my issue post).

**Comment by ryancasler** [comment]
Have you modified where the files are stored?   Or are you accessing the dashboard inside a docker container?  Because the button works for me from my desktop (not running GAR).  The file is being pulled from the local location but that's also where the webpage comes from.  So, I'm not sure why it's not working for you.

**Comment by michaelarnauts** [comment]
It's indeed running in a docker container (with the hass.io add-on). Everything on the interface works, except the playing of audio files. I think it could easily be fixed if you use relative urls (/file.wav instead of http://host:port/file.wav). The browser should use the currently used host and port then.

**Comment by greghesp** [comment]
Fixed in PR https://github.com/greghesp/assistant-relay/pull/149

v3.1.4 should resolve this

**Comment by Apipa169** [comment]
The Hassio addon will be updated soon!

**Comment by ryancasler** [comment]
That's odd...because I too am running in a docker container and have no problem playing audio files.  Are you using a special network connection for GAR in Docker or something?

**Comment by greghesp** [comment]
To be honest, it was poor coding from my behalf! Issue is resolved now :)
