### ISSUE TITLE
Play music from assistant relay

### ISSUE THREAD

**Issue by bugiov** [greghesp/assistant-relay#151]
Hi, I should start playing music (e.g. from spotify) via assistant relay (sending request from my android application that I am developing for a university project), I have documented a bit and it seems that assistant sdk does not support this function, or at least in the first versions, are there any news by chance? How can I do to start playback from AR? Routines don't work ... Is there any chance that I will be able to insert assistan relay into my google home app?

**Comment by greghesp** [comment]
You cannot do this due to a limitation on the Google Assistant SDK.  I suggest reaching out to Google asking them to allow it on their SDK.  More people that do it, the higher chance they add it
