### ISSUE TITLE
Broadcast works once than can only do again after several minutes

### ISSUE THREAD

**Issue by fabricioavil** [greghesp/assistant-relay#153]
Hi,

When I use broadcast in GAR, it works once and then doesn't work again for a long time. After broadcasting with GAR, if I try to broadcast asking my Google Home hub to do it (or any Google mini or my phone), my Google Home hub accepts the commands, but nothing happens.

If I wait several minutes (something around 15min), then it starts working again. If I send the broadcast using my Google Home hub without sending via GAR first, I can send one broadcast after the other without any problem.

In the CLI or GAR GUI, it accepts the first and subsequent broadcasts without any error msg, eg: I get "success": true, but only the first msg works, the others don't broadcast. The speakers don't do any sound at all (eg: even that announcing sound starting the broadcast).

In the mean time after the first broadcast, if I send any command to my speakers via GAR or voice, except broadcast commands, it works without any problem (eg: ask the time, ask to play a song on all speakers, etc.).

So, it looks when I send using GAR, it blocks something related to broadcast till a timeout happens and allows my account to send more broadcasts. (maybe it is waiting the "reply"?)

fyi: from a previous broadcast ticket I saw, I don't have IPv6 enabled in my LAN or WAN.

Thank you!!!

**Comment by greghesp** [comment]
Can you check in your MyActivity dashboard on Google. 

I cannot replicate this one, and have been able to send several broadcasts from AR consecutively, followed by multiple broadcasts from my Home Hub

**Comment by fabricioavil** [comment]
Hi,
I checked my history and I have some msg with "Unknown voice command", I guess it is related to the failed broadcasts:

Assistant
Unknown voice command
Details

Yesterday at 2:00 PM

Assistant

Google Smart Display

I cant broadcast now to confirm because family is sleeping, but I'll confirm tomorrow during the day.

**Comment by ryancasler** [comment]
If looks like you have Do Not Disturb turned on for some of your devices.  Is that possible?

**Comment by fabricioavil** [comment]
hi Ryan,
my devices arent in "do not disturb" mode and they dont get set to it after my first voice broadcast.
btw, if they were in DND, the first broadcast would already fail.

I did some additional test today, and I got the same/similar problem even when I only used google mini, so it isnt GAR. I guess it might be related to broadcast in the Asus AiMesh.

**Comment by ChrisJohns-me** [comment]
I've got this exact same problem, and have been troubleshooting for hours.
However, broadcasting seems to work consistently after 2+ minutes, rather than your 15 mins.

The only difference is I've got Netgear Nighthawk R6400v2 with 4 Google Home Minis.
But yeah, the only conclusion I've also come to is that it isn't GAR.
