### ISSUE TITLE
Delay in Brodcasts

### ISSUE THREAD

**Issue by adas4190** [greghesp/assistant-relay#16]
Hi, I really like your project it's very useful, keep up good work!
The only issue I face is that I have 3 Google Homes and very often I get a delay before each one of them give anouncement. Is there any thing that I can do to minimise the lag?
Thank You

**Comment by phvajjha** [comment]
Have the same issue. @adas4190 do you run your server on a Raspberry Pi by any chance?

**Comment by phvajjha** [comment]
I run it on the original pi. Maybe resources is the issue? ssh into the pi itself also has a slight delay in my case.

Try skipping npm and run the server directly using "node index.js". Npm seem to just sit there using resources. If my theory about this being a pi resources issue is right, this should help a bit.

**Comment by ryancasler** [comment]
Original Pi doesn't have ARM7 just ARM6.  Google Assistant requires ARM7.
That's why I couldn't get it to work on my Pi Zero W either.  😢

**Comment by phvajjha** [comment]
Posted this on the community forum, here is what I had to do:

"Assistant sdk depends on grpc which was not building right for v6 chips. Found a solution here - https://github.com/grpc/grpc/issues/132581"

Been running since 5 days now... Just this one delay issue that's bugging me.

**Comment by ryancasler** [comment]
You don't mention how long the delay is.  I'm still a little confused on how you got this to work on the Pi Zero if the Assistant SDK requires Arm7.  That is most likely what is causing your delay issue.

**Comment by greghesp** [comment]
As far as I'm aware, this is Google and not the relay. 
If you see the console log out that the message has been sent, then it's been sent to Google for processing.

If the delay is after that message, then unfortunately there's nothing that can be done.  If its from sending the request to the relay and seeing the message, then can you let me know the device

**Comment by adas4190** [comment]
Sometimes delay is greater sometimes smaller. It might depend I think how
busy my network is.

Thank You for help

**Comment by greghesp** [comment]
Is it after the confirmation messages show up in the console, or before?

**Comment by phvajjha** [comment]
My case, the delay is between 10 secs to 2 secs. This is the time between a sensor's state changing to me hearing something on the Google Home devices. Using webCoRE. Not using the SmartApp, so direct POST requests from the piston. Static IP configured to the server device (Pi).

It's always the first trigger that is slow to run. So, yes, this could be a network thing, i.e. webCoRE slow in making the first IP connection to the node server on Pi (for some yet unknown reason) after a decent period of inactivity. End result, I unlock the front door, come in, lock it and then hear both "lock" and "unlock" related announcements in succession after about 10 secs of my first unlock action.
I then unlock the door again within 1-2 mins, and this time there is minimal delay (2 secs max).

I will make a point to check the logs next time, to see if the delay is before or after your server prints out its message. I have it logging to a file and running in background on the Pi.

**Comment by greghesp** [comment]
Closing this.  I experience this too but unfortunately theres not a lot I can do.  The request goes off to Google and it seems they send the broadcast request in sequence rather than simultaneously.
