### ISSUE TITLE
New OAuth file

### ISSUE THREAD

**Issue by tunerooster** [greghesp/assistant-relay#163]
**Describe the bug**

I need to install a new authorization file, downloaded from Google.  How can I reset things so it asks me for the username, file, codes like it did at the beginning?

I am running 3.3.0b

p.s., broadcast is not working so I am hoping a fresh json file will help!

**Comment by tunerooster** [comment]
Anyone?

**Comment by ryancasler** [comment]
Go to the dashboard and select "New User".

**Comment by greghesp** [comment]
There's also an option in the dashboard to remove a user
