### ISSUE TITLE
cannot read property 'converse' of undefined

### ISSUE THREAD

**Issue by RohanG0407** [greghesp/assistant-relay#165]
**Describe the bug**

When I try to run the hello world command from sandbox, I get cannot read property 'converse' of undefined. Is this related to the fact that after I added my credentials.json and username and hit next it never took me to step 3 token?  

**To Reproduce**
1. Go to http://192.168.0.203:3000/home
2. Click on Sandbox
3. Enter your user, command as hello world, and broadcast

**Expected behavior**
I expected to hear a broadcast from my google home. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24467483/75615740-181a3400-5b16-11ea-9f91-088a8388364a.png)

![image](https://user-images.githubusercontent.com/24467483/75615748-3122e500-5b16-11ea-82a5-477781dcbcf7.png)

**Desktop (please complete the following information):**
-  Platform = Windows
 - Browser Firefox
 - Version v3.3.1b

**Additional context**
Which creditionls.json am I supposed to use to verify my user? The one from Device Registration or the one from OAuth screen?

**Comment by Shero-Inc** [comment]
@RohanG0407  Please what did you do to fix your issue ?

**Comment by mojotaker** [comment]
@RohanG0407  Please what did you do to fix your issue?

**Comment by RohanG0407** [comment]
Hey so essentially when setting up the id and after uploading the client secret file and hitting next it never took me to the submit token phase. This was because I had pop ups blocked on my browser. After I reenabled popups and hit next, It took me to the google screen to authorize and submit my token. Everything went fine from there
