### ISSUE TITLE
Swedish conversation language

### ISSUE THREAD

**Issue by fredamn76** [greghesp/assistant-relay#167]
Is it possible to add swedish conversation language? I really need it.

**Comment by ryancasler** [comment]
The Google Assistant Service is only supported in a select set of languages.  Any additional languages would have to be supported by the Assistant SDK.
https://developers.google.com/assistant/sdk/reference/rpc/languages
I don't see Swedish on that list.  You would have to make a request to Google to add it.  Sorry.

**Comment by greghesp** [comment]
Closing as answered by @ryancasler
