### ISSUE TITLE
do not disturb on a single device

### ISSUE THREAD

**Issue by paulsri** [greghesp/assistant-relay#168]
hi greg, from what i gather this is likely not possible, but just to confirm:

can you send a custom command to just one google home device? my use case is i want to enable do not disturb on one google home device _only_. i currently accomplish this with a routine that i setup that is spoken only to the device i want to put in DND mode. 

so if this routine is broadcast via the API, how does that work? or maybe it doesn't?

thanks!

**Comment by ryancasler** [comment]
You cannot do this from the Assistant Relay.  That is a limitation of the Assistant SDK which the relay is based on.  There are much greater restrictions on the SDK than on Google Home devices.   For example, you can issue a broadcast to your home speakers from your phone but you can only issue broadcasts to speakers on your local network from Google Assistant Relay.

**Comment by paulsri** [comment]
much thanks, greg. i'm going to see if the arbitrary / custom command i
send Assistant Relay can contain the specific Google Home device target,
like "set do not disturb on kitchen display", that way, i can achieve the
same result. or maybe a routine like "run my routine called DND on kitchen
display"

**Comment by ryancasler** [comment]
#1 this isn't Greg...
#2, neither of those commands will work from Google Assistant Relay.  I have tried both and neither will work.  You cannot set Do Not Disturb and you cannot execute routines.  Routines are based on matching your voice...can't match your voice in a text request.

**Comment by paulsri** [comment]
1) sorry just saw that. D’oh. I was looking at the to: line which shows the
github repo username.

2) thanks. I tried tonight as well. Just wish google would allow targeted
routines or targeted DND. oh well.

3) using assistant relay with flic HTTP request action now. Super awesome.

Thanks, Ryan.

— Paul
