### ISSUE TITLE
Add support for more languages

### ISSUE THREAD

**Issue by henrikrox** [greghesp/assistant-relay#169]
**Is your feature request related to a problem? Please describe.**
Frustrated that norwegian language isnt supported it worked with version 2.0. When i set nb-no in the config, it stops working.

**Describe the solution you'd like**
Add support for other languages.

**Comment by ryancasler** [comment]
Norwegian is not on the list of supported languages for the Google Assistant SDK.  I would recommend you request this from Google as GAR is limited to what languages they have implemented.

![image](https://user-images.githubusercontent.com/30270489/77833558-b351f980-7114-11ea-8ecd-59c23c79a406.png)


That listing can be found [here](https://developers.google.com/assistant/sdk/reference/rpc/languages).

**Comment by greghesp** [comment]
As per Ryan's comment, Norwegian isnt a support language.  The code to the SDK hasn't changed though, so this likely wasn't working in v2
