### ISSUE TITLE
Support to delete voice artifacts

### ISSUE THREAD

**Issue by hanlongwang** [greghesp/assistant-relay#170]
The wav files for the broadcast responses ends up using a lot of disk space after a while. Would love to have a feature to clear these.

**Comment by greghesp** [comment]
It should only be storing 5 items maximum. Is that not happening?

Can you let me know what platform your running it on please?

**Comment by ryancasler** [comment]
I'm on a Raspberry Pi and I see 8 wav files in my Audio responses folder.  I know I've issue a lot more broadcasts than that though, so something must be cleaning them up.

**Comment by greghesp** [comment]
This should be happening as per this function:
https://github.com/greghesp/assistant-relay/blob/master/relay/helpers/server.js#L105

If you let me know what OS etc then I can take a further look. @ryancasler  it should only be a maximum of 5.  There isn't any audio response from a broadcast, only when you ask questions etc

**Comment by ryancasler** [comment]
But there is.  It says "All right, broadcasting now."  And i can access that on the dashboard.  It appears that it had 3 files in there from March 15th, the other 5 were from today.  So, I cleared out the 3 really old ones, issued a new broadcast and it deleted the oldest of the 5 and replaced it with "All right, broadcasting now."  So, it definitely gets an audio response from a broadcast that it keeps and it is only keeping 5.

**Comment by greghesp** [comment]
Oh really, I didn't realise that 😂

@hanlongwang what OS?

**Comment by hanlongwang** [comment]
@greghesp I was using docker inside a Ubuntu server.  It might be permissions related, I went back to v2, but I'll try v3.2.0 again and see.

**Comment by greghesp** [comment]
Did this resolve?

**Comment by greghesp** [comment]
Found the issue, will fix in v4
