### ISSUE TITLE
Any way to broadcast without username?

### ISSUE THREAD

**Issue by Crazy1van** [greghesp/assistant-relay#171]
I know this is probably a design decision by Google, but is there any workaround to avoid broadcasts being preceded by “broadcast to user”?   Can I just have it say something?  

Great work, by the way.   

Thanks.

**Comment by ryancasler** [comment]
Google limitation, unfortunately.

**Comment by greghesp** [comment]
As per Ryans comment. Google enabled it server side with no way to disable it:

https://greghesp.github.io/assistant-relay/docs/other/faq#how-do-i-disable-incoming-broadcast-from-name
