### ISSUE TITLE
API response includes audio, but often does not include response text.

### ISSUE THREAD

**Issue by admoseremic** [greghesp/assistant-relay#173]
**Describe the bug**
Often, assistant relay will not return the text of the response even if it was valid. For example, asking "who is batman" will return the full text of the response, but asking "why is milk white" will give the correct audio, but no text in the response.

**To Reproduce**
Compare the responses of "who is batman" vs "why is milk white".

**Expected behavior**
I would expect the text to be included in both cases.

**Screenshots**
REQUEST:
`{
    "command": "who is batman",
    "converse": false,
    "user": "trevor"
}`
RESPONSE:
`{
    "response": "Here's a brief\nBatman (Fictional superhero). Batman is a fictional superhero appearing in American comic books published by DC Comics. The character was created by artist Bob Kane and writer Bill Finger, and first appeared in Detective Comics #27 in 1939.\nWikipedia ( https://en.m.wikipedia.org/wiki/Batman ).",
    "audio": "/server/audio?v=1586655767431",
    "success": true
}`

vs

REQUEST: 
`{
    "command": "why is milk white",
    "converse": false,
    "user": "trevor"
}`
RESPONSE:
`{
    "response": "",
    "audio": "/server/audio?v=1586655440539",
    "success": true
}`

**Desktop (please complete the following information):**
-  Platform: Ubuntu 18.04
 - Just using Postman
 - Version 3.2.0

**Comment by ryancasler** [comment]
There's nothing that Assistant Relay can do about that.  That is what is received back from the Assistant Service. You would have to request a change from Google.

**Comment by greghesp** [comment]
As per @ryancasler comment.  The response text is controlled by Google. If there is a response, it will log it out
