### ISSUE TITLE
Constantly querying github

### ISSUE THREAD

**Issue by gthrift** [greghesp/assistant-relay#177]
I'm running 3.3.2b on a raspberry pi along with pihole and a few other services.  I am seeing constant queries to github every 3ms.  I've shutdown every process one at a time and have narrowed it down to assistant-relay.  

![image](https://user-images.githubusercontent.com/4450552/82059298-d4a28100-9693-11ea-8c30-93efc95fac7e.png)

**Comment by greghesp** [comment]
Are you sure you haven't got multiple instances running?  I've just logged out the function calling Github and I can't replicate this .

The only things to call the function that checks if an update is available runs from a Cron job ```

```
cron.schedule("0 1 * * *", function() {
  if(isUpdateAvailable) console.log(`An update is available. Please visit https://github.com/greghesp/assistant-relay/releases`);
});
```

or when you load the About page via the Dashboard

**Comment by gthrift** [comment]
You're right, I had two instances running.
