### ISSUE TITLE
Some commands report blank text instead of "No text response given, click play to hear the audio"

### ISSUE THREAD

**Issue by davokr** [greghesp/assistant-relay#180]
Some commands such as "What time is it?" return a blank string instead of "No text response given, click play to hear the audio" or the correct response.

Confirmed on v3.3.2b

**Comment by ryancasler** [comment]
This is not AR, this is the Google Assistant.  It does not provide a text response to all requests.  Remember, The Google Assistant is not text based.  It's audio based.

**Comment by greghesp** [comment]
I thought we spoke about this on Discord and I identified the issue.  Now I'm looking at it, I cant see the issue I thought I previously found.
When asking "What time is it?" it doesn't reply a text response for me.

**Comment by greghesp** [comment]
I think this is partially linked to https://github.com/googlesamples/assistant-sdk-nodejs/issues/13  as well.  Will implement a string length check

**Comment by greghesp** [comment]
[Fixed in v4](https://github.com/greghesp/assistant-relay/commit/9171090aae7c6f30782ba71e2ae39ab0dccbfdb6#diff-a66074481455914ddaa1a2db3e5de43b)
