### ISSUE TITLE
Documentation link down?

### ISSUE THREAD

**Issue by Boyer2010** [greghesp/assistant-relay#183]
Not a bug with code but does anyone have a working link to the V3 documents?

**Comment by 6uhrmittag** [comment]
The link in the Readme is working, but the Doc itself seems to be not fully set up. You need to click on the "Cocs" link in the top left corner:https://greghesp.github.io/assistant-relay/

direct link: https://greghesp.github.io/assistant-relay/docs/introduction

**Comment by greghesp** [comment]
Thanks.  I updated the version of the documentation framework I was using, and it seems to have wiped half the content on the homepage..  Will fix
