### ISSUE TITLE
Cast Not Found

### ISSUE THREAD

**Issue by 1h8fulkat** [greghesp/assistant-relay#189]
**Describe the bug**
I am unable to post a request to /cast or /cast/search.  I am redirected back to /home when I browse to that path.

**To Reproduce**
1. Install assistant-relay supervised add-on for hass.io
2. Post the following JSON to http://<homeassistant>:3000/cast using NodeRed
```
{
device: '192.168.10.21',
source: 'http://<homeassistant>:3000/server/audio?v=1594315720582',
type: 'remote'
} 
```

**Expected behavior**
I except the device to begin casting the audio hosted at the source URL.

**Desktop (please complete the following information):**
-  Platform: HassOS 4.10, Assistant Relay 0.7.4
 - Browser Chrome
 - Version 0.7.4

**Additional context**
I am using NodeRed to post JSON to the Assistant Relay container.  Everything works except /cast which throws the following log errors.

0|www  | {
0|www  |   device: '192.168.10.21',
0|www  |   source: 'http://server.domain.com:3000/server/audio?v=1594315720582',
0|www  |   type: 'remote'
0|www  | } {}
0|www  | ClientError [NotFoundError]: Not Found
0|www  |     at /assistant_relay/app.js:41:8
0|www  |     at Layer.handle [as handle_request] (/assistant_relay/node_modules/express/lib/router/layer.js:95:5)
0|www  |     at trim_prefix (/assistant_relay/node_modules/express/lib/router/index.js:317:13)
0|www  |     at /assistant_relay/node_modules/express/lib/router/index.js:284:7
0|www  |     at Function.process_params (/assistant_relay/node_modules/express/lib/router/index.js:335:12)
0|www  |     at next (/assistant_relay/node_modules/express/lib/router/index.js:275:10)
0|www  |     at /assistant_relay/node_modules/express/lib/router/index.js:635:15
0|www  |     at next (/assistant_relay/node_modules/express/lib/router/index.js:260:14)
0|www  |     at Function.handle (/assistant_relay/node_modules/express/lib/router/index.js:174:3)
0|www  |     at router (/assistant_relay/node_modules/express/lib/router/index.js:47:12) {
0|www  |   message: 'Not Found'
0|www  | }
0|www  | POST /cast - - ms - -
0|www  | POST /cast - - ms - -
0|www  | POST /cast - - ms - -
0|www  | POST /cast - - ms - -

**Comment by ryancasler** [comment]
The URL you are passing to AR for the audio file is http://server.domain.com:3000/server/audio?v=1594315720582?  That doesn't appear to be correct.   The URL you send to AR should be where the file is hosted.  Port 3000 is where AR is expecting the requests to be received.  It's not an HTTP server for your files as well.  Try casting a valid url to AR.

**Comment by greghesp** [comment]
> The URL you are passing to AR for the audio file is http://server.domain.com:3000/server/audio?v=? That doesn't appear to be correct. The URL you send to AR should be where the file is hosted. Port 3000 is where AR is expecting the requests to be received. It's not an HTTP server for your files as well. Try casting a valid url to AR.

AR passes an audio URL back in the response. If you call that URL it will stream the file back to the browser or whatever called it.

@1h8fulkat in your /bin/audio-responses folder, can you see a file with the same name as the timestamp? 1594315720582.wav

**Comment by 1h8fulkat** [comment]
@greghesp if I access the AR container, I see all of the wav files in /**data**/audio-responses including the 1594315720582.wav file

**Comment by greghesp** [comment]
I think thats the issue.  The code looks for it in /bin/audio-responses.  @Apipa169 Is this something you modified with the HA container?

**Comment by 1h8fulkat** [comment]
I haven't modified the container at all.  The container was installed via the HASS supervisor addon-store using the repo here: https://github.com/Apipa169/Assistant-Relay-for-Hassio.  Will wait for @Apipa169 's response before I try to modify the volume mount.

**Comment by Apipa169** [comment]
Yes, that location is being modified to make sure the file won’t be removed after a restart.

But casting is only supported in the beta release of the add-on.

**Comment by 1h8fulkat** [comment]
@Apipa169 - great, thanks for that clarification, I didn't notice that it wasn't available outside of Beta.  

I have been able to get it to work by referencing the local file only.  I had to write a NodeRed function to parse the command POST response so I could reference the local directory.  For those interested, the function is:

```
var file = msg.payload.audio;
var res = file.split("=");
msg.url = "/data/audio-responses/"+res[1]+".wav";
return msg;
```
I then set the JSON with a change node and send to the POST node.  The entire flow is as follows, connect the function to the command POST node:
`[{"id":"226a260f.e7b60a","type":"function","z":"9208b996.c075c8","name":"Set Entity","func":"var file = msg.payload.audio;\nvar res = file.split(\"=\");\nmsg.url = \"/data/audio-responses/\"+res[1]+\".wav\";\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":940,"y":800,"wires":[["84792bc0.1b8688"]]},{"id":"84792bc0.1b8688","type":"change","z":"9208b996.c075c8","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\t   \"device\":\"google assistant IP\",\t   \"source\": msg.url,\t   \"type\":\"remote\"\t}","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1220,"y":720,"wires":[["dbac2d2f.7f45f"]]},{"id":"dbac2d2f.7f45f","type":"http request","z":"9208b996.c075c8","name":"post","method":"POST","ret":"obj","paytoqs":"ignore","url":"http://server:3000/cast","tls":"","persist":false,"proxy":"","authType":"","x":1430,"y":660,"wires":[["639765be.38caec"]]}]
`
The remote type referencing the AR media URL does not work, which is fine, just don't know if that is expected behavior.  I tested remote URLs for an internet MP3 file and it works as expected.
