### ISSUE TITLE
IFFTT /customBroadcast text is always undefined

### ISSUE THREAD

**Issue by dherran** [greghesp/assistant-relay#19]
Not sure if this is a bug in relay or in IFTTT.

Sending a POST request from Postman works fine. However, if you create a Webhook in IFTTT, the server receives the request but the text is always "undefined".

This is how I am setting it up in IFTTT:

URL: http://MY_IP:3000/customBroadcast
Method: POST
Content-Type: application/json
Body: 
{"user": "danny", "text": "hello"}

I also tried:

URL: http://MY_IP:3000/customBroadcast
Method: POST
Content-Type: application/x-www-form-urlencoded
Body: 
user=danny&text=hello

If I console.log() the request inside the customBroadcast closure, the query property is always empty, no matter what you put in the body.

The only way I managed to get this to work, is to simply enter the params in the URL field and leave the body empty. Not sure how the body is being sent from IFTTT or if they are sending it at all.

**Comment by ryancasler** [comment]
I believe this is an issue in the way that IFTTT bullds the URL it uses for the request.  I have seen similar issues with other apps using the Webhooks Service in IFTTT.  Try putting everything in the URL field. Try :http://MY_IP:3000/customBroadcast?text={broadcast text}&user={user name}

**Comment by dherran** [comment]
Yeah that's the only way I could get it to work. I was playing around with a different endpoint and noticed that ifttt is not sending a body with the request. I'll close and report the bug to ifttt.
