### ISSUE TITLE
Get light bulb status.

### ISSUE THREAD

**Issue by bikotoru** [greghesp/assistant-relay#196]
There is some way to be able to obtain the status of a light bulb, to know if it is on or off.

**Comment by ryancasler** [comment]
You can get it to speak the status of a light bulb.  But I assume you mean to report it back to the requesting system.  That is not possible.  This is not a backdoor to full control of Google connected devices by other systems.

**Comment by bikotoru** [comment]
> You can get it to speak the status of a light bulb. But I assume you mean to report it back to the requesting system. That is not possible. This is not a backdoor to full control of Google connected devices by other systems.

Thank you. Another query.
Do you know any way to use the google home bulbs from Hassio as bulbs that are integrated?
To be able to know the status, change color, etc.
Or how to create an entity with a google home device to turn a light bulb on or off.

**Comment by ryancasler** [comment]
No.  Google Assistant does not allow for outside systems to control devices.  It connects to devices to control them.  This is the architecture of the system and the way it was designed.
