### ISSUE TITLE
Google Assistant can now broadcast to specific devices.

### ISSUE THREAD

**Issue by saxobroko** [greghesp/assistant-relay#197]
**Is your feature request related to a problem? Please describe.**
Now that this officially supported maybe we could see this feature added sometimes?

**Describe the solution you'd like**
When sending a broadcast we have an additional "Speaker Name" to add.

**Additional context**
https://support.google.com/googlenest/answer/7531913

**Comment by hsandhar** [comment]
@greghesp mentioned it under [Casting](https://greghesp.github.io/assistant-relay/docs/cast/casting) that this is a work in progress, but readily available in [v3.3b](https://github.com/greghesp/assistant-relay/releases/tag/v3.3.2b).


![I tried it out](https://i.imgur.com/C0lDJZ8.png)


I believe you can [pass either the IP or the device name](https://github.com/skorokithakis/catt/blob/433b7e97e55d9d09c5097b361e1090c219843b1c/catt/api.py#L21), and it should work.

Don't forget to enable casting in config.

**Comment by greghesp** [comment]
@hsandhar that's for casting not broadcast.

This is already on V4, however you can work around it in v3 by sending a broadcast, then for the message just do `to the bedroom speaker, this is a broadcast`

**Comment by hsandhar** [comment]
It's my bad. I misread.
