### ISSUE TITLE
can not access the url provided by assistant relay

### ISSUE THREAD

**Issue by nanudul** [greghesp/assistant-relay#198]
**Describe the bug**
I can not access the url given by assistant relay, when setting it up. The browser just says "The website is not available" after loading for a while.

**To Reproduce**
1. Download the release.zip from "https://github.com/greghesp/assistant-relay/releases"
2. Unzip the zip into a folder.
3. Open terminal or a comand window and run "npm run setup"
4. Then run "npm run start"
5. click on the url given by the terminal/ assistant relay

**Expected behavior**
Being able to load the url and then set up assistant relay.

**Desktop (please complete the following information):**
-  Platform Windows 10
 - Browser Chrome, Edge, Internet Explorer
 - Version 3.3.2 also 3.2.0

**Comment by hsandhar** [comment]
What kind of error/info message do you see when the browser launches when you go to that url?

**Comment by nanudul** [comment]
Hi,

I solved it!
It turned out that some part of my VPN was still running even though I had
closed it.
Thanks anyways.

Am So., 16. Aug. 2020 um 03:18 Uhr schrieb Harjot Sandhar <
notifications@github.com>:
