### ISSUE TITLE
Web server

### ISSUE THREAD

**Issue by zacharystg** [greghesp/assistant-relay#199]
Hi, I wish I could put this project on a web server for myself. The problem is there's no authentication.

I would like us to be able to log in with credentials to access the web page and all the content. Also I would like to be able to have an authentication token to allow me to be the only one to have access to the api.

Thank you and have a nice day!

**Comment by greghesp** [comment]
AR will only work on an external server if you want to use it for queries only, you cannot use any of the broadcasting or casting functionality of it.  It was designed to run on a local server in your home network.

That being said, the v4 branch which is currently a work in progress supports dashboard authentication and api keys
