### ISSUE TITLE
Add ability to set volume of the announcement 

### ISSUE THREAD

**Issue by Danabw** [greghesp/assistant-relay#2]
Request (once API supports it) for ability to set the volume of the announcement. Ideally the volume setting affects the announcement only, and the volume on the GH is not changed for existing music streaming, etc.

**Comment by kmickeletto** [comment]
This would be dynamite!

**Comment by ryancasler** [comment]
The announcement is at the GH current volume.  Whatever content you are playing is lowered before the notification.  So, you can do this (and I do).  You would have to first issue a custom command to "set volume to $". Then issue the broadcast.

**Comment by greghesp** [comment]
Closing this.  Just send a command asking it to "Set volume to x%"
