### ISSUE TITLE
issue setting up latest version of the relay

### ISSUE THREAD

**Issue by AnuragJindal** [greghesp/assistant-relay#20]
I was working with an older version of the relay till today. I downloaded the latest version of the relay and ran build-config. but it gives me following error:

pi@raspberrypi:~/GoogleRelay/assistant-relay-master $ npm run build-config

> assistant-relay@1.0.1 build-config /home/pi/GoogleRelay/assistant-relay-master
> node configBuilder.js

/home/pi/GoogleRelay/assistant-relay-master/configBuilder.js:30
    let secret = result['Client Secret File Name'];
    ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Any help is appreciated. Thanks!

**Comment by chathurangawijetunge** [comment]
Same here. Earlier it was working fine.
Do we have to re name client secret file ???
What's going on....?

**Comment by ryancasler** [comment]
Yes.  The instructions state you have to add the username at the beginning of the filename.  This is to allow multiple users (and therefore multiple secret files) to be used together.

**Comment by chathurangawijetunge** [comment]
Where to add the user name....? To what file...? Not clear.

**Comment by ryancasler** [comment]
Follow these instructions.
https://github.com/ryancasler/assistant-relay/wiki/Install-Instructions

**Comment by greghesp** [comment]
Not sure if this is still an issue. If so, can you reopen this
