### ISSUE TITLE
Casting custom mp3 is erratic

### ISSUE THREAD

**Issue by xsherlockpl** [greghesp/assistant-relay#202]
Hi,
Casting a custom mp3 file (including the release included doorbell,mp3) works once in 3-4 times.

Sometimes if I'm lucky I will hear the  doorbell but most of the time I only get introduction casting blip a bit of silence and exit blip.

{
    "device": "Living Room speaker",
    "source": "doorbell.mp3",
    "type": "custom"
}

I also tried with IP instead off name of the speeker and results are similary erratic. 
Same results from the sandbox page  and  when invoked remotely with curl.

I'm running version v3.3.2b on Ubuntu 18.04

Maciej

**Comment by greghesp** [comment]
Hey,

If you're getting the casting "dink" sound, then AR is doing it's part.  It's using [CATT](https://github.com/skorokithakis/catt) on the backend, so I'd suggest raising an issue over there

The command it's calling will be `catt -d "Living Room speaker" cast doorbell.mp3`

**Comment by xsherlockpl** [comment]
Thanks for the explanation, kind of I missed that,   I will look into troubleshooting catt,  Can I update catt while not touching assistant relay?

**Comment by greghesp** [comment]
Yep. AR just installs CATT via Python if its not already installed
```
if(s.exec(`${pip} install catt`).code !== 0) {
```
