### ISSUE TITLE
Broadcast to specific device

### ISSUE THREAD

**Issue by ndoty** [greghesp/assistant-relay#205]
Google now supports broadcasting to a specific device(s). Can this support be added to assistant relay now?

**Comment by ryancasler** [comment]
It already is.  All you have to do is specify the device you want to broadcast to in your message.  If you are using the sandbox, do not check "broadcast" and just type in the message field "Broadcast to <Name of device> <Message>." just make sure the name matches what is in Google Home EXACTLY.  

I think Greg is working on something for v4 to make this a lot easier but this is a good stop-gap until v4 is ready for prime time.  ;-)

**Comment by ndoty** [comment]
Okay i feel a little silly now as i didn't even think to try that. I was over complicating it by thinking i needed to pass assistant relay a variable for the device just like you do with broadcast. Never thought I could just pass it in the command and don't set the broadcast flag.. I tested this with the rest command in Home Assistant and works perfectly. Thanks for the reply.

**Comment by ndoty** [comment]
> It already is. All you have to do is specify the device you want to broadcast to in your message. If you are using the sandbox, do not check "broadcast" and just type in the message field "Broadcast to ." just make sure the name matches what is in Google Home EXACTLY.
> 
> I think Greg is working on something for v4 to make this a lot easier but this is a good stop-gap until v4 is ready for prime time. ;-)
