### ISSUE TITLE
Cannot read property 'converse' of undefined

### ISSUE THREAD

**Issue by Hike-Up** [greghesp/assistant-relay#207]
Hello,

posting any message to the server always returns 
"Cannot read property 'converse' of undefined"

I have tested all possible configuration of broadcast and converse, the result is always the same.

I am running on raspberry 4

Any help?

Thanks

**Comment by ryancasler** [comment]
Are you able to broadcast messages from the dashboard?  can you paste in what the URL and JSON body you are trying to send to Assistant Relay? That's the only way that anyone will be able to tell what you might be doing wrong.

**Comment by ryanlchan** [comment]
Just ran into the same bug. For me it was that my username had a typo in it when POSTing to the /assistant endpoint, which caused the call to fail with this error.

Fix was to either 1) remove the username (which looks like it just defaults to the first user) or 2) exact match the registered name to the username param.

**Comment by Hike-Up** [comment]
Thanks, that's the trick! 
I have simply removed the username and it works.
I  have not figured out yet what the user username is (email and name are not working) but it doesn't matter.
