### ISSUE TITLE
greg_client_secret.json still being referenced

### ISSUE THREAD

**Issue by frakman1** [greghesp/assistant-relay#21]
Test platform: MacBook Air on OS X Sierra (10.12.6)

Despite running the build-config script, I still get an error due to the code looking for your credentials file

I just removed it and now it works but I thought you might want to update your code.

```bash
$npm run build-config

> assistant-relay@1.0.1 build-config /Users/frak/git/assistant-relay
> node configBuilder.js

What do you want to do? (Enter 1 or 2):
1) Add User
2) Change port
Number: 1
prompt: Name:  AssRelay
prompt: Client Secret File Name:  client_secret_xxxxx.apps.googleusercontent.com.json

            Your config file has now been saved!
            When needed, use the username assrelay to send Google Assistant commands from this users account

$npm run start

> assistant-relay@1.0.1 start /Users/frak/git/assistant-relay
> node index.js

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'C:\Users\Greg\Documents\Projects\assistant-relay\greg_client_secret.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at new Auth (/Users/frak/git/assistant-relay/node_modules/google-assistant/components/auth.js:26:15)

$grep -rnIw --color=always ./ -e "greg_client_secret.json"

.//config.json:1:{"language":"en-US","users":{"greg":{"keyFilePath":"C:\\Users\\Greg\\Documents\\Projects\\assistant-relay\\greg_client_secret.json","savedTokensPath":"C:\\Users\\Greg\\Documents\\Projects\\assistant-relay\\greg-tokens.json"},"assrelay":{"keyFilePath":"/Users/frak/git/assistant-relay/client_secret_xxxxx.apps.googleusercontent.com.json","savedTokensPath":"/Users/frak/git/assistant-relay/assrelay-tokens.json"}},"port":"3000"}
```

**Comment by ryancasler** [comment]
Works fine for me. Did you clone the repo or manual download and install?

**Comment by frakman1** [comment]
I just cloned it now.

lol, of course it works for you mate. It's looking for a file only you have. 😄

**Comment by ryancasler** [comment]
No, actually it doesn't.  I'm not Greg.

**Comment by ryancasler** [comment]
When you do this, you are changing the filename to your username, right?

**Comment by AnuragJindal** [comment]
when you add user by using the command:

node configBuilder.js


It adds a new user on top of the default existing user (greg). Just
open the file config.json in a text editor and remove the content
related to default user greg. Just keep your user name etc. It will
work.

**Comment by ryancasler** [comment]
Or just build your own config.json with the tool.  No need to edit.  😀

**Comment by frakman1** [comment]
@ryancasler Forgive me if I missed it, but the instructions in the README.md say:
```
Once you have downloaded your client secret file, copy it to the root folder of this project.
```
Can you point me to where it says to rename it?

**Comment by frakman1** [comment]
I was responding to your comment:
![image](https://user-images.githubusercontent.com/5826484/39191107-1eb95e30-47a4-11e8-8024-4a4040f21350.png)


Raising an issue where something doesn't work as expected isn't complaining, it's called reporting. 

The idea is that other smart people who run into a similar issue and error message can search the issue list and find a solution so we can all be smart together.

**Comment by greghesp** [comment]
Fixed
