### ISSUE TITLE
Quiet hours not respected on change of day

### ISSUE THREAD

**Issue by sti0** [greghesp/assistant-relay#218]
**Describe the bug**
I set quiet hours from 21:00 to 07:00. After 00:00 the quiet hours are not respected any more.

If I set start time to 00:01 quiet hours are respected again. Therefore it must be a bug on the calculation after changing the day at 00:00.

**To Reproduce**
1. Go to 'Configuration'
2. Activate "Quiet hours"
3. set quiet hours for e.g. 21:00 to 07:00
4. wait till midnight
5. broadcast a message
6. Google Home turns on and broadcasts the message

**Expected behavior**
Within quiet hours no broadcast should happen.

**Screenshots**

**Desktop (please complete the following information):**
-  Platform Home Assistant Addon
 - Browser Chrome
 - Version v3.2.0

**Additional context**

**Comment by laurens1991** [comment]
I am experiencing exactly the same issue (the same version installed 3.2.0). I woke up due to this ;)
