### ISSUE TITLE
converse=true doesn't seem to work.

### ISSUE THREAD

**Issue by frakman1** [greghesp/assistant-relay#22]
Test platform: MacBook Air on OS X Sierra (10.12.6)

When I try the command with `converse=true`, I still see the response in the console window instead of hearing the response from Google Assistant.

```
$http POST http://127.0.0.1:3000/custom?command=what+time+is+it&user=xxxx&converse=true
[1] 9240
[2] 9241
[2]+  Done                    user=xxxx
$HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 65
Content-Type: application/json; charset=utf-8
Date: Tue, 24 Apr 2018 03:19:54 GMT
ETag: W/"...."
X-Powered-By: Express

{
    "command": "what time is it",
    "message": "Custom command executed"
}
```

On the window running the `npm run start` command, I see this response:

```
Received command what time is it
No user specified, using xxxx
Google Assistant: The time is 11:19 PM.
```

For some reason, it doesn't acknowledge my supplied username, although it uses it anyway.

**Comment by ryancasler** [comment]
Yes it does.  I just did the same command and it worked fine.  You are replacing XXXX with your username, correct?  Are you changing the IP that your ordering it to?  What are you using to send the command to your relay?

**Comment by frakman1** [comment]
@ryancasler 
1- Yes, I am replacing xxxx with my username.
2- The command is running on the laptop that the endpoint is running on hence the 127.0.0.1, so I don't need to change the IP address.
3- I am not assuming it doesn't work. I am merely reporting my results. To that end, I have provided a log of my command syntax and the log of the endpoint response. The result is the same whether or not I use `converse=true`.
4- I can get the `customBroadcast` commands to work (Google Assistant repeats those words) so I know everything else is working end-to-end.

**Comment by frakman1** [comment]
For anyone else running into this issue, I forced it to work with this workaround:

in index.js around line 62
Change the line:
```js
  //Check the converse parameter
  if(converse) returnAudio = true;
```
to:
```js
  //Check the converse parameter
  returnAudio = true;
```

I was able to get it to work then.
When I ask it to tell me a joke however, I only get the punch line. Probably a limitation of the tool.

**Comment by ryancasler** [comment]
Adding the converse=true parameter works for me just fine.

**Comment by qreeves** [comment]
> When I ask it to tell me a joke however, I only get the punch line. Probably a limitation of the tool.
The code seems to split multi-line responses to avoid the "more info" stuff from spitting out.

**Comment by greghesp** [comment]
It seems that this only works on some things for some reason.  I'm not 100% sure why at first glance.
Try asking "What time is it?" as I know this one works.

Will have to investigate why the other stuff doesn't work.  Maybe there is no response from the SDK because it can't handle certain things yet

**Comment by frakman1** [comment]
hi @greghesp. Thanks for responding. I have found that it behaves differently based on the http tool being used and all the various parameter/options that get set. I still couldn't get it to work via the `http` command but when I used an iOS app called `iCurlHTTP`, it worked fine.

Can you please update the README.MD to include the correct `curl` syntax to do this and the other customBroadcast command? I think it would helpful for people to be able to use a standard command instead of the hodge-podge that everyone is using today leading less that helpful 'works for me' comments.

Thanks

**Comment by ryancasler** [comment]
That's because your browser issues GET requests and the relay only accepts POST requests.   You do not need to use curl but you need to use something that issues POST commands, such as Postman.

**Comment by greghesp** [comment]
Ryan is correct

Use [Postman](https://www.getpostman.com/) if you want to mess around.  I have a Postman [Collection](https://www.getpostman.com/collections/42fe420662d38f74a45e) you can import and change to suit your environment

**Comment by frakman1** [comment]
I am not using a browser. When I said that I used `http`, I meant that I use the command line tool `httpie` detailed [here](https://httpie.org/). I even included the output of that command in the [original post above](https://github.com/greghesp/assistant-relay/issues/22#issue-317057206)

Thank you for sharing Postman and your Postman Collection. However, I still think the instructions should include working `curl` commands. Curl is pre-installed, works the same way and absolutely supports the options needed here. It gives a baseline that everyone can agree on. I don't have to install anything new. Moreover, I can script these commands in curl in a way that I can not with Postman.

** **UPDATE** ** I see that Postman has a `export to curl` functionality. When I get this to work, I will test the equivalent curl commands.

**Comment by ryancasler** [comment]
It's no fair when you answer your own question!!  😉 I will say this though about the code you'll get out of Postman, there is extra stuff that is included.  For example, this is what postman generates for one of my commands:
```
curl -X POST \
  'http://192.168.1.17:3000/custom?command=what%27s%20the%20temp%20outside?&user=ryan&converse=true' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: POSTMAN_TOKEN_REMOVED'
```
The two lines with "-H" are not actually needed to issue the curl command.  It works fine without them.  Also, here's another example of where converse = true works.  I use this to broadcast the temp at different times of the day.

**Comment by jmcgwire** [comment]
I'm seeing the exact same behavior as @frakman1.  I had been using curl -X POST, but retried using postman.  With converse=true, all answers are typed to the console but not announced on the speakers.

![image](https://user-images.githubusercontent.com/568061/42004434-b671c8f4-7a24-11e8-84f1-6e0da3e7109a.png)

Console:
No user specified, using jack
Google Assistant: The time is 4:04 PM.
Received command broadcast The time is 4:04 PM.
No user specified, using jack

**Comment by greghesp** [comment]
I think this was linked to the issue Google had with Broadcasts.  Im going to close this, but if its still an issue, please reopen
