### ISSUE TITLE
"Play Beatles on Kitchen Display" Gets "Sorry I don't understand"

### ISSUE THREAD

**Issue by jayhohoho2019** [greghesp/assistant-relay#220]
**Describe the bug**
From the browser sandbox, command="Play Beatles at Kitchen Display" doesn't play music at the Kitchen Display (a Google Home Display).  Audio response is "Sorry I don't understand."  

**To Reproduce**

**Expected behavior**
I expected Beatles music to be played on the Kitchen display, the same way as when I asked my Pixel phone to do the same.  

**Screenshots**

**Desktop (please complete the following information):**
-  Platform Ubuntu Linux 
 - Browser  Chrome
 - Version 3.2.0

**Additional context**
Would I need to upgrade to V3.3.b for this to work?  If so, how would an upgrade work if I already have V3.2.0 working (commands such as What time is it, or It's Dinner Time (broadcast), all work.).

**Comment by greghesp** [comment]
The SDK doesn't support certain things.  Asking it to play music is one of these unfortunately.

https://assistantrelay.com/docs/other/faq#how-can-i-cast-media
