### ISSUE TITLE
Can please someone tell me the difference between converse/relay/broadcast?

### ISSUE THREAD

**Issue by pickonedev** [greghesp/assistant-relay#227]
Hi!

I know that broadcast will broadcast a message, but what relay and coverse do? Thank you!

**Comment by littlbee** [comment]
Broadcast is to have your google home(s) speak out the message.
Relay allows to send a command to your Google Home/assistant without speaking, so for instance I would want to use this Assistant Relay to turn on a Philips Hue light. If I had "converse" to that command I send via a relay action, then Google Home would speak out the result of that action.
