### ISSUE TITLE
Assistant relay " This add-on is not available on your system."

### ISSUE THREAD

**Issue by Surgical17** [greghesp/assistant-relay#229]
**Is your feature request related to a problem? Please describe.**
I am unable to install Assistant relay on Home assistant 2021.1.5
-- Error is that "This add-on is not available on your system."

**Describe the solution you'd like**
To be available on my system

Device: Raspberry Pi 1 Model B
HA: 2021.1.5

**Comment by ryancasler** [comment]
This is not a AR issue, this is a Home Assistant issue.  I would post the issue on the HA forum.  This repo has no HA specific setup.
