### ISSUE TITLE
Can get it to work with a second user

### ISSUE THREAD

**Issue by TheBartoMan** [greghesp/assistant-relay#23]
I have two user setup on my google home.

I have set both the users up using npm run build-config

when i issue a command as a second user, it always reverts to the main user.

_Received command "Whats my name?"                                               
User specified was sarah                                                        
Google Assistant: Your name is Dave                                             
Received command broadcast Your name is Dave                                    
No user specified, using dave_                                                   
                           
Am I missing somthing please?

**Comment by ryancasler** [comment]
Can you post the POST message you are sending?

**Comment by TheBartoMan** [comment]
Am i missing something in order to get a second user working via the relay? i even tried adding sarahs google account to the project which im not sure is needed. (her email account is already a working user along with mine on google home. She can ask it whats her name and it works.)

**Comment by ryancasler** [comment]
You've created a oauth credentials file for her and added it to the same
folder as yours?

**Comment by TheBartoMan** [comment]
That must be the area i'm having the issue i guess. But when I downloaded the credenitals.json file for Sarah, the contents appear to be the exact same as the credentials file the i got when i downloaded mine. Am i getting them from the wrong place? Is the oauth the file you get from the location shown in the image? (credentials.json)
![edit-model](https://user-images.githubusercontent.com/28529964/39469286-59e22cc2-4d2f-11e8-8de4-a156dfcb3239.png)

The credentials.json file is the file i used when i added the users with **npm run build-config**

**Comment by ryancasler** [comment]
Did you make it under her Google account or yours?

**Comment by TheBartoMan** [comment]
i set it up under my account and got the credentials.json. i then ran npm run build-config and added the user dave with the credentials.json file.

I then added sarah do the project as an owner (not sure thats needed?) 

I then logged into the project as sarahs gmail account and downloaded the credentials.json file again (the contents seem to be the same as mine)

then i ran npm run build-config again and added the user sarah with the credentials.json file.

Am i doing something wrong? is that the correct file i needed to download to use with build-config?

**Comment by ryancasler** [comment]
Why would you think it would know her name from your account?  it is using her as the user...but you've set it up so that both users are YOU!  you have to set it up under her account.  that's the only way it knows what her name is.

**Comment by TheBartoMan** [comment]
Not sure that makes sense....

My google home is setup with two users. Dave and Sarah. It works perfect at home as normal and the voice match knows who is who. 

I then read about this relay and want to set it up so I can post commands as either user. 

I set it all up in my dave account and it works fine. I then wanted to add the second user (sarah) so I can post commands ending ?user=sarah and get appropriate responses. 

But as you can see from my original post when i issue a command as Sarah, it still responds as dave. 

I want to know what I’ve done wrong? 

One question I have is :- 

Is the file “credentials.json” the file you need for Laura?

It’s the file i used when I setup the first user dave and that worked. 

But the file seems to be the same contents if I download it when logging into the project with Sarah’s gmail account.

**Comment by ryancasler** [comment]
You're not even going to try what I told you to do?  Then I'm not going to help you any more.  The reason the google home can answer sarah correctly is that her account is linked to the google home.  If you use the same oauth file for both users, they are both linked to the same account.  Google assistant doesn't know that Sarah is the same as user=sarah.  That's for the relay to pick which oauth file to use when making the request of the assistant.
But don't listen to me....i'm just trying to help you.  

****Requesting a close to this issue.****

**Comment by TheBartoMan** [comment]
Apologies. I missed the bit about the different project as I read the message from my phone. I will try that and report back. Thank you

**Comment by TheBartoMan** [comment]
Could you explain if it’s possible to get both an oauth file for dave and an oauth file for sarah from the same project? Or is it one project per person?

**Comment by ryancasler** [comment]
What difference does it make?!??!  Why are you intentionally making this so complicated?  I'm not getting paid to answer your questions.  This isn't even my damn program.  LMAO

**Comment by TheBartoMan** [comment]
Im not sure why you are so upset? And i don't see how I'm making this complicated.

I appreciate I don't understand the oauth process. The documentation I can find isn't clear and doesn't show how to have two users on the project, hence I asked the simple question.

I simply wanted to know how you get two oauth files for two users as i cant make it work as the second user.

If you don't know the technical answer, I am happy to wait till someone with an understanding of the issue can help.

I said I am happy to try creating a second project with the second user as you suggested, but then you replied saying "Doesn't have to be a different project."

If it doesnt need to be a second project, I still dont understand how you get two oauth files from one project.

**Comment by greghesp** [comment]
You need to setup a new project under Sarah's Google account, in the same way you set it up for yours.

Log out of your Google account entirely. If you're adding Sarah as a user to your project, then I think it's essentially using your Google Account - not 100% sure on this though

**Comment by TheBartoMan** [comment]
Thank you for your simple answer. Much appreciated.

**Comment by TheSnook** [comment]
This is a very old issue, but I thought I'd comment for anyone having trouble and browsing for answers. So here it is:

**_There's absolutely no need to create multiple Google Cloud projects for multiple users, nor even to create multiple OAuth credentials._**

The OAuth secret belongs _to the application itself_. The token represents whichever user logged in to the Google OAuth page after visiting the URL that assistant-relay provides. Each instance of assistant-relay really only needs on secret, but the code is set up to expect one per user.

So, you if you already have a user "fred" you can just copy secrets/fred.json to secrets/wilma.json unmodified. Restart and assistant-relay will kick off another OAuth workflow for user "wilma". Give the URL to Wilma, have her log in to Google, approve the access and give you back the token.

**Comment by MrHollowX** [comment]
> This is a very old issue, but I thought I'd comment for anyone having trouble and browsing for answers. So here it is:
> 
> **_There's absolutely no need to create multiple Google Cloud projects for multiple users, nor even to create multiple OAuth credentials._**
> 
> The OAuth secret belongs _to the application itself_. The token represents whichever user logged in to the Google OAuth page after visiting the URL that assistant-relay provides. Each instance of assistant-relay really only needs on secret, but the code is set up to expect one per user.
> 
> So, you if you already have a user "fred" you can just copy secrets/fred.json to secrets/wilma.json unmodified. Restart and assistant-relay will kick off another OAuth workflow for user "wilma". Give the URL to Wilma, have her log in to Google, approve the access and give you back the token.

This worked perfectly. You saved me at least 30 minutes of pointless work mentioned above.
