### ISSUE TITLE
Can you issue tasks?

### ISSUE THREAD

**Issue by TheBartoMan** [greghesp/assistant-relay#24]
I can ask it to broadcast things, I can ask to tell me things such as the time.

Is there any way to action things? Such as "Set the volume to 20"

**Comment by ryancasler** [comment]
You can issue the command as follows:

`http://IP:PORT/customCommand?command=YOUR COMMAND HERE&user=USERNAME&converse=true
`


However, the response will be broadcast on all Google Home devices in your network.  There is currently no method to select which one.

**Comment by TheBartoMan** [comment]
Im guessing you mean custom?command as opposed to customCommand?command  ?

Unfortunately the relay seems to work with when you ask questions like "Tell me the time", but doesn't seem to work if you want to ask it to do something such as "Set the volume to 30% on all speakers"

Is there a way to do things such as set the volume via relay commands? (Its not a limitation of Google Home as I can say the same command to the speaker and it also works if i type it into Google Assistant app)

**Comment by DanDon** [comment]
I think this is not possible as this is a web server hooked into the Assistant API from Google and can only utilize the broadcast feature. You may notice that it is not account dependant either:
For example ... 
How long to get to work?
This doesn't work as it requires using you personal setting for work location on your Google account. That isn't possible using the broadcast feature. Only non-account specific questions.

**Comment by greghesp** [comment]
You could try this without using the broadcast feature and use the custom feature.
Some stuff will work, other things wont work.  

I've tested the time to work feature, and it seems to log it fine in the My Activity pane, but it wont feedback to the SDK for some reason

![image](https://user-images.githubusercontent.com/768908/40361053-f08f6f18-5dbf-11e8-98ef-7eebee3aad17.png)
