### ISSUE TITLE
Unable to start assistant relay

### ISSUE THREAD

**Issue by krishna383** [greghesp/assistant-relay#27]
I am getting the following error
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle assistant-relay@1.0.1~prestart: assistant-relay@1.0.1
6 info lifecycle assistant-relay@1.0.1~start: assistant-relay@1.0.1
7 verbose lifecycle assistant-relay@1.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle assistant-relay@1.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/assistant-relay/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle assistant-relay@1.0.1~start: CWD: /home/pi/assistant-relay
10 silly lifecycle assistant-relay@1.0.1~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle assistant-relay@1.0.1~start: Returned: code: 132  signal: null
12 info lifecycle assistant-relay@1.0.1~start: Failed to exec start script
13 verbose stack Error: assistant-relay@1.0.1 start: `node index.js`
13 verbose stack Exit status 132
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid assistant-relay@1.0.1
15 verbose cwd /home/pi/assistant-relay
16 verbose Linux 4.4.48+
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 132
22 error assistant-relay@1.0.1 start: `node index.js`
22 error Exit status 132
23 error Failed at the assistant-relay@1.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 132, true ]
```

```pi@krishna-rpi:~/assistant-relay $ sudo npm run start

> assistant-relay@1.0.1 start /home/pi/assistant-relay
> node index.js

Illegal instruction
npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! assistant-relay@1.0.1 start: `node index.js`
npm ERR! Exit status 132
npm ERR! 
npm ERR! Failed at the assistant-relay@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-13T23_02_11_255Z-debug.log```

**Comment by ryancasler** [comment]
Which model Raspberry Pi?  Assistant Relay isn't supported on Pi Zero or Zero W because Google Assistant SDK requires ARM 7 and the Zero and Zero W are ARM6.

**Comment by jdtoth** [comment]
Getting the below error when attempting to start it. The directory its referencing doesn't exist. Any ideas?

`
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/volume1/homes/******/assistant-relay-master/node_modules/grpc/src/node/extension_binary'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.<anonymous> (/volume1/homes/******/assistant-relay-master/node_modules/grpc/src/grpc_extension.js:37:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/volume1/homes/******/assistant-relay-master/node_modules/grpc/src/client.js:38:12)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assistant-relay@1.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the assistant-relay@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-19T03_20_55_053Z-debug.log
`

**Comment by greghesp** [comment]
Looks like you're running on an unsupported environment

**Comment by szh** [comment]
For anyone else trying to get assistant-relay running on a Raspberry Pi Zero W, per a few comments around Github, you need to run
```
npm rebuild grpc --build-from-source
```
which will take several hours to rebuild it for armv6.
(If you're using SSH to run these commands, I recommend using `nohup npm rebuild --build-from-source grpc > log.txt &` for the rebuild command in case your connection is interrupted during the very long build process.)

However... when I try to configure assistant-relay I get an error:
```
node /home/pi/assistant-relay/bin/www: symbol lookup error: /home/pi/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v72-linux-armv6l-glibc/grpc_node.node: undefined symbol: __atomic_store_8
```

**Comment by ryancasler** [comment]
So....you are, in fact, not able to use Assistant Relay on an RPi Zero?

**Comment by szh** [comment]
@ryancasler Correct. I can get past the "Illegal instruction" error on start, but in the end it fails once I try to configure it from the web UI.
