### ISSUE TITLE
Did anyone else begin experiencing issues?

### ISSUE THREAD

**Issue by ryancasler** [greghesp/assistant-relay#296]
Noticed that I am no longer getting broadcasts as of today, April 4th, 2024.  Is anyone else experiencing this problem?  Everything was working until today.

**Comment by mjarends** [comment]
Yep - just noticed the same thing. Glad I'm not the only one.

**Comment by ryancasler** [comment]
It seems that the issue has resolved itself.  I guess it was a bigger problem.  Folks on Home Assistant were having problems too.
