### ISSUE TITLE
Stopping Nest stream command doesn't work

### ISSUE THREAD

**Issue by DanDon** [greghesp/assistant-relay#30]
The command to stop a Nest stream doesn't work and neither does using a custom command to ask Google to "stop <chromecast name>.

Using voice on any Google Home and saying "stop <chromecast name>" does stop the Nest cam stream though??

**Comment by greghesp** [comment]
This one was always a bit of a pain because the way Google gets you to stop a stream doesn't actually work, so I have to make a workaround.

How are you stopping the stream via voice?  The relay sends the command "Stop <chromecast name>"

**Comment by DanDon** [comment]
Ah. That has obviously been changed by Google too then because that is the voice command I'm using. It is also the command I tried with a custom command and every variation.

All the voice commands that work to stop the stream, do not work through the relay.

**Comment by greghesp** [comment]
Sigh.. 

Just to check.. Are you passing the chromecast name to the relay, not the camera name

**Comment by DanDon** [comment]
Yes. The command I pass is:

http://IP:PORT/custom?command=stop+chromecast&user=dan

Yes I have called my Chromecast 'chromecast' for the minute just for testing. I have also tried:

stop+stream
stop+showing+me+the+camera
turn+off+Chromecast

These all work by voice 😔

**Comment by DanDon** [comment]
Unfortunately this is still not working ... although everything else seems to be

**Comment by greghesp** [comment]
I'm going to have to close this one for now. It seems like a limitation on the Assistant SDK and its not something i have control over unfortunately
