### ISSUE TITLE
error when use npm run build-config

### ISSUE THREAD

**Issue by naseemr** [greghesp/assistant-relay#31]
I am getting the following error after I do the command npm run build-config.

npm run build-config

> assistant-relay@1.0.1 build-config /home/naseemr/Documents/assistant-relay
> node configBuilder.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'prompt'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/naseemr/Documents/assistant-relay/configBuilder.js:2:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assistant-relay@1.0.1 build-config: `node configBuilder.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the assistant-relay@1.0.1 build-config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/naseemr/.npm/_logs/2018-05-23T22_45_45_123Z-debug.log

Here is the detail log:
05-23T22_45_45_123Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build-config' ]
2 info using npm@6.0.1
3 info using node@v8.11.2
4 verbose run-script [ 'prebuild-config', 'build-config', 'postbuild-config' ]
5 info lifecycle assistant-relay@1.0.1~prebuild-config: assistant-relay@1.0.1
6 info lifecycle assistant-relay@1.0.1~build-config: assistant-relay@1.0.1
7 verbose lifecycle assistant-relay@1.0.1~build-config: unsafe-perm in lifecycle true
8 verbose lifecycle assistant-relay@1.0.1~build-config: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/naseemr/Documents/assistant-relay/node_modules/.bin:/home/naseemr/bin:/home/naseemr/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle assistant-relay@1.0.1~build-config: CWD: /home/naseemr/Documents/assistant-relay
10 silly lifecycle assistant-relay@1.0.1~build-config: Args: [ '-c', 'node configBuilder.js' ]
11 silly lifecycle assistant-relay@1.0.1~build-config: Returned: code: 1  signal: null
12 info lifecycle assistant-relay@1.0.1~build-config: Failed to exec build-config script
13 verbose stack Error: assistant-relay@1.0.1 build-config: `node configBuilder.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid assistant-relay@1.0.1
15 verbose cwd /home/naseemr/Documents/assistant-relay
16 verbose Linux 4.13.0-43-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build-config"
18 verbose node v8.11.2
19 verbose npm  v6.0.1
20 error code ELIFECYCLE
21 error errno 1
22 error assistant-relay@1.0.1 build-config: `node configBuilder.js`
22 error Exit status 1
23 error Failed at the assistant-relay@1.0.1 build-config script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ryancasler** [comment]
You do know that the relay doesnt currently work, right?  The Google Assistant SDK needs to be patched before it will work. So, even if you get the install complete you won't be able to test it.

**Comment by naseemr** [comment]
ah, ok, any idea when SDK will be patched?

**Comment by ryancasler** [comment]
Nope.  There's another issue opened on it.  Stay tuned.

**Comment by greghesp** [comment]
Fixed by Google. 
Did you manage to resolve this?

**Comment by naseemr** [comment]
I am out of country now. Will check when I get back. Thanks.

**Comment by mkono87** [comment]
I just grabbed your package and getting the exact same issue

**Comment by greghesp** [comment]
Are you still having the same problem?

Did you run `npm i` first?
If you still have the issue, can you try typing in `npm i prompt` and then try again?

**Comment by mkono87** [comment]
No its working fine now. I think it was few dependencies I was missing.
