### ISSUE TITLE
Add option to get an audio response for custom commands

### ISSUE THREAD

**Issue by caj380** [greghesp/assistant-relay#32]
Hi, Would it be possible to add the option to get an audio response for custom commands.
I like the "converse" function, but for requests like "Tell me a Joke" it cuts off the punchline and sounds a little robotic. It also broadcasts the response to the entire house.
It would be awesome if I could send a POST request to http://127.0.0.1:4000/custom?command=tell+me+a+joke&user=chase and get back an mp3 file with the assistant's response. That would mean I could just tell WebCORE to "Play Track: http://127.0.0.1:4000/custom?command=tell+me+a+joke&user=chase" on my kitchen speaker.

I was able to add the audio functionality to assistant relay and get it to play through the speakers of the computer I'm running it on as a test. However, I don't know NodeJS and I can't seem to figure out how to convert the audio buffer to a mp3 stream. Any help would be greatly appreciated.

Thanks,
Chase

**Comment by ryancasler** [comment]
Without trying to, you discovered the reason why your request won't work.
The assistant relay is acting like another home device.  That's why it
works.  So, when you don't enter converse, only the home device that
received the query, in this case it is Assistant Relay, will respond.  So,
I would say that your request is not only outside the scope of the project
but also outside what is allowed by the Google Assistant SDK.

**Comment by caj380** [comment]
My apologies, I think you misunderstood what I meant. I am aware that it is acting as a separate virtual google home. When I run a custom command like http://127.0.0.1:4000/custom?command=tell+me+a+joke&user=chase it responds with the text:
"How does our solar system keep its pants up?
With an asteroid belt"
in the terminal. What I would like is to add the option to get the audio that the google assistant sdk returns of her saying that as a file/stream.
I don't know NodeJS or I would do it myself and submit a pull request. However, I was able to get Assistant Relay to play the response audio out the speaker of the computer I was running it on:
https://youtu.be/USdXxtz3njk
I just want it to return that as and mp3 file/stream rather than saying it out my speakers since this will be running on a headless server.

Thanks for all the help :)

**Comment by ryancasler** [comment]
Why?  Why not just speak the command to your Google Home? This is a
limitation of the Assistant SDK and not Assistant Relay.  I'd say, if you
want that, send the request to Google.

**Comment by caj380** [comment]
It is not a limitation of the Google assistant SDK. It is already fully supported by Google and it is completely possible using the example provided by endoplasmic in the library this uses: https://github.com/endoplasmic/google-assistant . As you can see in the video I sent all I did was add a few lines and it returned the audio from the google assistant sdk.

What is your opinion @greghesp ?

**Comment by greghesp** [comment]
@caj380 is correct.  The assistant provides this back to the assistant relay.
I would need to test it as I can't recall how exactly it works off the top of my head.  Did you try adding the converse parameter to the request?

**Comment by caj380** [comment]
@greghesp Thank you. Adding the converse parameter preforms a broadcast of the text response. I use that feature at the moment but what I was hoping for is to be able to make a request with something like "&audio=true" and have the assistant relay respond with the mp3 audio response from google. Here is the code I used to get the audio response to play from the speakers.

https://gist.github.com/caj380/16792dab2645145ee5794e3d35334f5b

I don't know NodeJS so pardon me if it's messy.

Thanks for all the help!

**Comment by greghesp** [comment]
I'll have to look at this as you can't pass an MP3 to be played.

I think it provides a text version of the response too so it might be possible to broadcast that, but that won't help if you ask it what a dog sounds like

**Comment by caj380** [comment]
Oh okay. So there's no way to make a request like:
http://127.0.0.1:4000/custom?command=tell+me+a+joke&user=chase
and get back something like this (the file, not the link):
https://transfer.sh/E6h7s/relay.mp3

**Comment by greghesp** [comment]
Not that I'm aware of unfortunately.  If you ask the assistant to tell you a joke, it should send the response back through the speaker if you use the converse parameter.

I'm having to break out the response to remove the unneeded text from the response though here: https://github.com/greghesp/assistant-relay/blob/master/index.js#L202

I wonder if that's affecting the response..

**Comment by caj380** [comment]
I actually got a _sort of_ working version of what I want. It works fine for me but if you try to make multiple requests it fails. I started to add temp ids and things to handle multiple requests but I eventually gave up as I don't know NodeJS. I published a fork. Please excuse the messy code.
https://github.com/caj380/assistant-relay

If you make a get or post request like this:
http://127.0.0.1:4000/custom?command=Tell+me+about+my+day&user=chase&audio=true
It returns an audio file of the response. That way I can just use WebCoRE to make my bedroom speaker "Play Track: http://127.0.0.1:4000/custom?command=Tell+me+about+my+day&user=chase&audio=true"
![image](https://user-images.githubusercontent.com/3978865/44158232-3c243a80-a082-11e8-95b9-651f654577ac.png)
 I also added TTS functionality so you can make a request like:
http://127.0.0.1:4000/tts?text=Testing+1+2+3&user=chase
Ang get back a audio clip of Google assistant saying that.

Hopefully you can clean up my code and integrate it in assistant relay.

Thanks for all the help,
Chase

**Comment by greghesp** [comment]
Hey @caj380 

I got the audio file written.  I'm assuming Bedroom Speaker is a Sonos device or something rather than a Google Home?

**Comment by greghesp** [comment]
@caj380  Closing this as its been implemented in V2.
The response contains an audio field which has a URL to play the audio response

**Comment by caj380** [comment]
@greghesp Thank you! This looks great. But is there any way you can add a dedicated audio path so I can keep making requests the same way in WebCoRE? For example, a URL with form data in it that directly returns an audio file? Also could you add in my TTS functionality? I made a modified version of the Cast Web API device handler that allows me to use that TTS function (provided it directly returns a file) to allow any SmartThings app to use the Google assistant voice for Text to Speech. Thanks so much for the fantastic work!

**Comment by greghesp** [comment]
@caj380  It overwrites the file and only sends a response when its finished.

You can do it like so.  Unfortunately you seem to need to pass the random ?v parameter, otherwise the audio file gets cached.

![image](https://user-images.githubusercontent.com/768908/44353105-f3afb700-a49d-11e8-805b-f833e750583b.png)

**Comment by caj380** [comment]
Okay. Thank you. I never would have figured that out. Also, what do you mean by the ?v parameter? I don't see it in the piston.

**Comment by greghesp** [comment]
You won't see it in the piston.  The response from Assistant Relay is JSON, so if you use the `$response[audio]` parameter in WebCore, it'll take whatever URL Assistant Relay gives you.

**Comment by irabeamte2** [comment]
i am trying to get 'tell me about my day' to work. is this command not supported? 

curl -d '{"command":"tell me about my day", "user":"leondutton", "converse":"true"}' -H "Content-Type: application/json" -X POST http://192.168.0.15:3200/assistant
{"audio":"http://http://192.168.0.15:3200/audio?v=31","success":true}
no response from google 

stupid jokes work
curl -d '{"command":"tell me a joke", "user":"leondutton", "converse":"true"}' -H "Content-Type: application/json" -X POST http://192.168.0.15:3200/assistant
{"audio":"http://http://192.168.0.15:3200/audio?v=88","response":"What do you call a labrador that becomes a magician?\nA labracadabrador 🐶 🎩 ✨","success":true}
(these jokes are really bad right?) 

am I missing something?

**Comment by caj380** [comment]
Hi @irabeamte2,
I've found that routines are not supported for some reason. However that one will run if you say "Good Morning". Let me know if that works for you.

**Comment by HootyMammoth** [comment]
@greghesp I currently have the assistant relay up and running properly on my PI....thanks for sharing that code by the way. I can send commands via postman to send broadcasts or control devices just fine. However, when I try to send an HTTP POST via webCore I get the following errors in webCore and ST. Thoughts on what I need to change to get this to work?

![image](https://user-images.githubusercontent.com/50126259/57275042-d7bb6800-7062-11e9-804b-23b94aae76fd.png)

![image](https://user-images.githubusercontent.com/50126259/57275073-ed309200-7062-11e9-88eb-3cbb5b36bc99.png)

Here is how I have webCore setup:
![image](https://user-images.githubusercontent.com/50126259/57275116-0d605100-7063-11e9-8c1e-5075ac1cf47c.png)
