### ISSUE TITLE
Cannot GET /customBroadcast

### ISSUE THREAD

**Issue by alxbouchard** [greghesp/assistant-relay#33]
Any hints?

`pi@raspi:~/assistant-relay $ npm run start

> assistant-relay@1.0.1 start /home/pi/assistant-relay
> node index.js

Fired up the SSDP Server for network discovery...
Firing up the Web Server for communication on address 10.10.10.53:3000
Assistant Relay is now setup and running for zap
Received command broadcast Assistant Relay is now setup and running for zap
No user specified, using zap
`

**Comment by greghesp** [comment]
Use /POST, not /GET

**Comment by alxbouchard** [comment]
Oups… Thanks it work perfectly! 

:)
