### ISSUE TITLE
custom commands will not work when playing music to GH

### ISSUE THREAD

**Issue by jpoeppelman1** [greghesp/assistant-relay#34]
I'm able to ask what the weather is as well as broadcast messages on my LAN, but custom commands will not work when requesting to play music (i.e. nothing happens). Please see below. When will this be fixed?

Thanks
James

Fired up the SSDP Server for network discovery...
Firing up the Web Server for communication on address 192.168.1.138:3000
Assistant Relay is now setup and running for assistantgateway-assistantgateway-s0vh5u
Received command broadcast Assistant Relay is now setup and running for assistantgateway-assistantgateway-s0vh5u
No user specified, using assistantgateway-assistantgateway-s0vh5u
Received command play jazz on office home
No user specified, using assistantgateway-assistantgateway-s0vh5u
Received command what is the weather
No user specified, using assistantgateway-assistantgateway-s0vh5u
Google Assistant: Looks kind of cloudy
Currently in 45245 it's 70 and cloudy. Today, there'll be scattered thunderstorms, with a forecasted high of 81 and a low of 65.
( More on weather.com )
Received command broadcast Looks kind of cloudy
No user specified, using assistantgateway-assistantgateway-s0vh5u
Received command play jazz on office home
No user specified, using assistantgateway-assistantgateway-s0vh5u

**Comment by ryancasler** [comment]
When you issue that command to Relay, which Google home do you expect the music to play on? You can use converse=true to see if it will play on all of them but I doubt it will.  When you issue that command it will play on Assistant relay.  That's how it works.

**Comment by jpoeppelman1** [comment]
I have tried using the converse=true flag, but nothing happens. 

Interesting thing is if I disable my 4G connection on my Galaxy S9, then launch assistant and type "play jazz on office home", then it works fine and plays the music in my office!  How can we mimic this behavior through Assistant Relay?  I ask because I'm trying to automate certain GH actions based on SmartThings routines.

http://192.168.1.138:3000/custom?command=play jazz on office home&converse=false

Thanks,
James

**Comment by ryancasler** [comment]
Assistant relay uses the broadcast functionality of the Google assistant.  I would suspect that your phone's default music player is the home in your office.  That's why it's able to play when you command it to.  However, broadcasts don't work like that.  It broadcasts to all devices on your account.  I would look at something called Cast-web-api.  That might be more of what you're looking for with music control.

**Comment by jpoeppelman1** [comment]
My GH in my office is not my default music player..  Obviously the cmd is
hitting the cloud and coming back to my LAN given I disabled wifi when
testing.

On Jun 29, 2018 9:51 AM, "ryancasler" <notifications@github.com> wrote:

Assistant relay uses the broadcast functionality of the Google assistant. I
would suspect that your phone's default music player is the home in your
office. That's why it's able to play when you command it to. However,
broadcasts don't work like that. It broadcasts to all devices on your
account. I would look at something called Cast-web-api. That might be more
of what you're looking for with music control.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/greghesp/assistant-relay/issues/34#issuecomment-401360418>,
or mute the thread

**Comment by greghesp** [comment]
Won't be fixed.  The Assistant SDK from Google doesn't currently support the ability to cast/play music for some reason
