### ISSUE TITLE
Google down again!??!?

### ISSUE THREAD

**Issue by ryancasler** [greghesp/assistant-relay#36]
Several folks, including me, over at the ST community are reporting that broadcasts have stopped again.  Have you heard anything?

**Comment by do1eh** [comment]
Here too! Other commands (like "What time is it?") work (I can see the answer in the console) but broadcasts did'not come through...but no errormessage... From phone (typing) or by voice broadcasts work fine.

**Comment by ryancasler** [comment]
I even tried re-installing from scratch.  That didn't help.  Still not able to get broadcasts.

**Comment by greghesp** [comment]
Closing as believe issue is resolved
