### ISSUE TITLE
Is there still an issue with google? 

### ISSUE THREAD

**Issue by naseemr** [greghesp/assistant-relay#38]
For some people there is no issues and for some I see they are still not able to hear the broadcast. 
I am not sure what is the real issue here, I even see PM2 logs that shows below but google home does not broadcast it.
0|index    | Fired up the SSDP Server for network discovery...
0|index    | Firing up the Web Server for communication on address 192.168.1.97:3000
0|index    | Assistant Relay is now setup and running for naseemra
0|index    | Received command broadcast Assistant Relay is now setup and running for naseemra
0|index    | No user specified, using naseemra

**Comment by greghesp** [comment]
If you can see the requests under My Activity on your Google account, then can you add to the issue here please:
https://github.com/endoplasmic/google-assistant/issues/52
