### ISSUE TITLE
tip for modify code

### ISSUE THREAD

**Issue by tarokker** [greghesp/assistant-relay#45]
Hi Greg, thanks fot sharing this fantastic project!!

I would like to dig inside the sources and hack it in order to test sending commands to a specific google home devices group (instead of all). Do you know where I should starting to look for?

I’m not asking for code, I know you’re busy and you already written than possible support for groups will be added in the future :)
I’m just curious for a hint maybe you’re already figure where to start looking for (your project? some modifications inside the dependencies library?)

Thanks for your time in advance

**Comment by greghesp** [comment]
Hi,
You can't unfortunately.  That's a limitation on the Google's side, and until they provide a method for us to do so, it's not possible.

There is a workaround, but its messy and probably not the best idea, also never tried it myself.  I've seen someone mention that they created a new Google Account for each room, and then linked that account to just 1 Google Home device.  They then added each Google Account to the Relay, and passed the user parameter to control which device to broadcast too.

Like I say, not something I've tried and its a bit hacky so I can't provide any help on it.  If Google open up the SDK to control broadcasts to individual devices (or another solution) then I'll add it in
