### ISSUE TITLE
no application type other

### ISSUE THREAD

**Issue by Daryl149** [greghesp/assistant-relay#48]
in the readme it says in bold:

**Note: When creating an Oauth Client ID, make sure you use the "Other" application type**

But there is no option 'other' to be found in the list.

**Comment by CloudPower97** [comment]
Hey there @Daryl149, I'm having the same issue. 
How did you manage to resolve it?
@greghesp I'm stuck at this point and can't continue ☹️

**Comment by Daryl149** [comment]
I'm sorry, but I can't recall anymore. I might actually have just stopped trying to make this repo work. Hope you found a solution in the meantime.
