### ISSUE TITLE
Conversation Error: { Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. 

### ISSUE THREAD

**Issue by AdamJWood** [greghesp/assistant-relay#51]
Thank you for this app, I love it!  I've been using assistant-relay for a couple days for a few home automation tasks but get an occasional error.  Once it throws the error it repeats every 9th request over the course of a couple hours.  I am unable to duplicate the issue by spamming requests over a short period of time.  It seems every ninth request over an undetermined extended period of time triggers the error.  I can work around the issue but if you have any insights as to the source of the problem I would greatly appreciate it.  Thanks

```javascript
Received command set thermostat to 70 degrees
User specified was myhomecontrols
Conversation Error: { Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at Object.exports.createStatusError (C:\assistant-relay-master\node_modules\grpc\src\common.js:87:15)
    at ClientDuplexStream._emitStatusIfDone (C:\assistant-relay-master\node_modules\grpc\src\client.js:235:26)
    at ClientDuplexStream._receiveStatus (C:\assistant-relay-master\node_modules\grpc\src\client.js:213:8)
    at Object.onReceiveStatus (C:\assistant-relay-master\node_modules\grpc\src\client_interceptors.js:1290:15)
    at InterceptingListener._callNext (C:\assistant-relay-master\node_modules\grpc\src\client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (C:\assistant-relay-master\node_modules\grpc\src\client_interceptors.js:614:8)
    at C:\assistant-relay-master\node_modules\grpc\src\client_interceptors.js:1110:18
  code: 16,
  metadata: Metadata { _internal_repr: { 'www-authenticate': [Array] } },
  details: 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.' }
```

**Comment by AdamJWood** [comment]
Yeah, I was under the impression I may be the only one with this particular issue; I couldn't find anything similar when googling it.  I just built an error check into another app that runs along side this to repeat the request when it fails to go through.  I'm currently running it on Windows 10 but I plan on moving it to another system that runs Linux - I suspect I'll have better luck with that.  Thanks

**Comment by greghesp** [comment]
My only suggestion would be to try and download a new OAuth file
