### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by Dabbadoeber** [greghesp/assistant-relay#52]
Hello Downloading and installing assitant-relay.
but failing at npm install.

what could be the problem ?

Thx.

pi@rasppi:~/Downloads/assistant-relay-master $ sudo npm install

> speaker@0.3.1 install /home/pi/Downloads/assistant-relay-master/node_modules/speaker
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/Downloads/assistant-relay-master/node_modules/speaker/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/Downloads/assistant-relay-master/node_modules/speaker/.node-gyp'
gyp ERR! System Linux 4.14.50-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/Downloads/assistant-relay-master/node_modules/speaker
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> grpc@1.8.0 install /home/pi/Downloads/assistant-relay-master/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-linux-arm-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.10.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-linux-arm-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.10.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/Downloads/assistant-relay-master/node_modules/grpc/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/Downloads/assistant-relay-master/node_modules/grpc/.node-gyp'
gyp ERR! System Linux 4.14.50-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/home/pi/Downloads/assistant-relay-master/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/pi/Downloads/assistant-relay-master/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc"
gyp ERR! cwd /home/pi/Downloads/assistant-relay-master/node_modules/grpc
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/pi/Downloads/assistant-relay-master/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/pi/Downloads/assistant-relay-master/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/Downloads/assistant-relay-master/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.14.50-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/Downloads/assistant-relay-master/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/pi/Downloads/assistant-relay-master/node_modules/grpc
node-pre-gyp ERR! node -v v10.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/pi/Downloads/assistant-relay-master/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/pi/Downloads/assistant-relay-master/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc' (1)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/Downloads/assistant-relay-master/node_modules/grpc/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/Downloads/assistant-relay-master/node_modules/grpc/.node-gyp'
gyp ERR! System Linux 4.14.50-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/home/pi/Downloads/assistant-relay-master/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/pi/Downloads/assistant-relay-master/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc"
gyp ERR! cwd /home/pi/Downloads/assistant-relay-master/node_modules/grpc
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN assistant-relay@1.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: speaker@0.3.1 (node_modules/speaker):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: speaker@0.3.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.8.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-07T11_24_59_474Z-debug.log
r

**Comment by AdamJWood** [comment]
Might try:
sudo npm install --unsafe-perm

**Comment by greghesp** [comment]
Can you try V2
