### ISSUE TITLE
presets not working using the given format

### ISSUE THREAD

**Issue by cogneato** [greghesp/assistant-relay#53]
To get the presets to work I have to use
`{"command": "lunch time", "user": "user", "broadcast": "true"}`

Using this doesn't work, or I'm missing something else.
`{"preset": "lunch time", "user": "user"}`

edit: Using v2

**Comment by AdamJWood** [comment]
https://github.com/greghesp/assistant-relay#preconfigured-broadcast

**Comment by greghesp** [comment]
Fixed in v2.0.1
