### ISSUE TITLE
Broadcasts are not played on devices

### ISSUE THREAD

**Issue by soldag** [greghesp/assistant-relay#55]
For my setup broadcasts are not working. When sending a broadcast command to the assistant-relay, I get a success response and I can even see the correct command in my Google Assistant activity feed, but the message is not played on the device. 

Does anybody has an idea, what causes this issue? Did I miss any configuration option?

**Comment by jimboca** [comment]
Do you have night mode enabled?  If so, disable it for now.  https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/googlehome/iMpcfFslvFE/_vSeG598EAAJ

**Comment by soldag** [comment]
No, sending broadcasts from my mobile phone using the Google Assistant app works, too.

**Comment by soldag** [comment]
I could solve the issue by disabling IPv6 on the device that runs assistant-relay as described in https://github.com/endoplasmic/google-assistant/issues/52.
