### ISSUE TITLE
Changing language in /server/configurations/config.json doesn't seem to do anything

### ISSUE THREAD

**Issue by haabe** [greghesp/assistant-relay#57]
I tried changing the language from "en-US" to "nb-NO" (Norwegian), but the audio had a distinct American accent.

I also tried changing the language to "pl-PL" (Polish), but the audio still had a distinct American accent.

I did shut down and restart the server inbetween modifying the config, of course.

**Comment by tschrover** [comment]
I can confirm the same issue. Tried changing the language to "nl-NL" and "de-DE" with no effect, speech stays "en-US".

**Comment by haabe** [comment]
There is one issue related to this. Endoplasmic/google-assistant's conversation.js uses params.lang, not params.language. Changing to conversation. lang in the config file causes an error if an unsupported language is used.

I still only get American English no matter which language I try from the list at https://developers.google.com/assistant/sdk/reference/rpc/languages

**Comment by umar-kh** [comment]
So I managed to fix the problem of language not changing in the audio files. I edited the conversations.js file in the google-assistant node-module folder and changed “en-US” to “en-GB” (in my case British English). It looks like the config.js for the relay isn’t changing the language properly.

**Comment by ryancasler** [comment]
What was the setting when you authorized AR?  I would suspect the setting has to be right when you set it up and wouldn't change later based on a change to that file.

**Comment by haabe** [comment]
@ryancasler You are correct! My Google Action Console project was only configured for English. After peeking around for a bit I found the language tab and included Norwegian as well. Now it works swell (I still use "conversation": { "language": "no-NO" } instead of "conversation": { "lang": "no-NO" } because of my previous comment.
