### ISSUE TITLE
Quiet hours does not work

### ISSUE THREAD

**Issue by jotielim** [greghesp/assistant-relay#60]
Setting the quietHours start to a number less than current hour will always end up in quiet hours because `start <= now`.
i.e. start = 0, end = 8, now = 21. This should not be quiet hours but it currently is.

I can open a PR to fix this if you want.

**Comment by djmannyfresh** [comment]
Is there a workaround for this? Thanks.

**Comment by djmannyfresh** [comment]
I ended up commenting out the part of the code that implements quiet hours.
Setting the start and end to 0 didn't work for me.

I actually ran into a different problem which I couldn't get past, in
WebCORE but it is not due to this component. So I kind of abandoned this
for now. But the relay did work otherwise.

**Comment by kmlucy** [comment]
I figured it out. It you delete the quiet hours parameter in the config file entirely it will be disabled.

**Comment by ogiewon** [comment]
I had the same issue with quiet hours.  The code for it is definitely buggy.  There has been a pull request with a quiet hours fix for many months now.  I haven't tested it personally, as I just deleted the quiet hours parameter as well to avoid the bug.

**Comment by inguy24** [comment]
Yeah I think I am going to bite the bullet and go the webcore route. 

⁣Get BlueMail for Android ​

**Comment by greghesp** [comment]
I thought I had fixed this, but maybe not.  Will add to next release

**Comment by satyendu2010** [comment]
Still getting quiet time response from the relay on V2.1.1. Not able to go past that point.  Was this fixed through the app.js script or some other way? Thanks

**Comment by greghesp** [comment]
Fixed in version 3.
