### ISSUE TITLE
loading in startup

### ISSUE THREAD

**Issue by naseemr** [greghesp/assistant-relay#61]
Hi, thank you for the assistant-relay. How can I use PM2 with this app?

**Comment by ogiewon** [comment]
I'd like to know the exact same thing.  @naseemr , did you ever figure it out?

**Comment by ogiewon** [comment]
I figured it out...

pm2 start server/app.js --name "assistant-relay-v2"
pm2 save

**Comment by ryancasler** [comment]
Does that have to be initiated whenever your Pi starts?  You have to add that to your rc.local or write a systemd service, correct?  or is there a pm2 service you can start?  It's still not clear to me how to use this instead.

**Comment by greghesp** [comment]
Just run `npm run start` if you have PM2.  If not, run `npm run goinstall` first and then `npm run start`
