### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ayasystems** [greghesp/assistant-relay#66]
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-linux-arm-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.14.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-linux-arm-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.14.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.14.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.14.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/assistant-relay/node_modules/grpc/build'
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/home/pi/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/pi/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc"
gyp ERR! cwd /home/pi/assistant-relay/node_modules/grpc
gyp ERR! node -v v10.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/pi/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/pi/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/assistant-relay/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.14.52-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/assistant-relay/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/pi/assistant-relay/node_modules/grpc
node-pre-gyp ERR! node -v v10.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok

**Comment by viknet365** [comment]
same issue here, but cannot help beeing a nodejs newbee

**Comment by PhunkMaster** [comment]
I just ran in to this and was able to fix. use node:8 for the docker container. Here is my Dockerfile for reference:
`FROM node:8

RUN git clone https://github.com/greghesp/assistant-relay.git
RUN apt update
RUN apt upgrade -y
RUN apt install -y build-essential

WORKDIR /assistant-relay

RUN npm install

COPY secret.json /assistant-relay/server/configurations/secrets/
COPY token.json /assistant-relay/server/configurations/tokens/

EXPOSE 3000`

**Comment by robwolff3** [comment]
@PhunkMaster What are the secret.json and token.json you refer to in your Dockerfile?

**Comment by greghesp** [comment]
You're using Node 10, but the built of Assistant in the package.json only allows for Node 8.
If you update your package.json file with `"google-assistant": "^0.5.3"`, it should work on Node 10
