### ISSUE TITLE
assistants array is blank - any ideas as to the cause? 

### ISSUE THREAD

**Issue by mxmerce** [greghesp/assistant-relay#69]
No errors from client, but I see errors in the google console.   

I'm trying to figure out how to enable logging to get specifics, only see that there was an error. 

  "__INSTRUCTIONS": "change port below to the port you want the app to listen on.  Set baseUrl to the address reachable from the google home devices to the app.  Normally this is just your server's IP and the specified port, but if you are running the app through a reverse proxy like nginx, you may have to tweak this setting.  One suggestion is to set up a dyndns.org name and install client on your server to update it any time your IP changes, then put the name in baseName instead of IP.",
  "port": "3500",
  "muteStartup": false,
  "baseUrl": "http://<hidden>:3500",
  "conversation": {
    "language": "en-US",
    "audio": {
      "sampleRateOut": 24000,
      "sampleRateIn": 24000
    }
  },
  "users": {
    "<hidden>": {
      "keyFilePath": "/home/ubuntu/assistant-relay/server/configurations/secrets/<hidden>.json",
      "savedTokensPath": "/home/ubuntu/assistant-relay/server/configurations/tokens/<hidden>-tokens.json"
    }
  },
  "assistants": {}
}

**Comment by waschbaer77** [comment]
I have the same problem and no idea how to log errors. 
Did you find an solution?

**Comment by dellop** [comment]
Same problem on ubuntu. I dont know what the array is supposed to look like.

**Comment by mmonti** [comment]
Exactly the same problem here...

**Comment by ndoty** [comment]
I am getting this too but i have tracked mine do to not even being able to authorize. I must be doing something wrong while setting up and downloading my Oauth json.

**Comment by vschi** [comment]
Same problem here. Not sure how it should look like as the instruction is missing any information what should be there in case everything is setup correctly.

**Comment by AtConnect** [comment]
Same problem here, the activity is registered in the google account, but no sound produced on the google home

**Comment by tenoriojuann** [comment]
The assistant object is blank in the file because it saves the assistant object in memory. I believe it is there just for referencing it in the code.

At least that's what I've seen in the code.

**Comment by greghesp** [comment]
Ah now I understand. Yes, the assistants object should be empty. The JSON gets loaded into memory and populated etc. I could technically remove it and generate the when it's loaded, but I haven't 😂
