### ISSUE TITLE
wont install

### ISSUE THREAD

**Issue by jckickflip** [greghesp/assistant-relay#71]
when I start ndm install I just get a bunch of warn followed by errors.
Your environment has been set up for using Node.js 10.14.2 (x64) and npm.

C:\Users\crystal>cd C:\Users\crystal\Desktop\assistant-relay-master

C:\Users\crystal\Desktop\assistant-relay-master>npm install
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\statuses-bc722e4d\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\statuses-bc722e4d\codes.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\statuses-bc722e4d\HISTORY.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\statuses-bc722e4d\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\statuses-bc722e4d\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\statuses-bc722e4d\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\plist-fb1274c5\examples\browser\index.html'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\plist-fb1274c5\.travis.yml'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\timers-ext-7715a6d1\test\promise_\.eslintrc.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\timers-ext-7715a6d1\test\promise_\timeout.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\plist-fb1274c5\examples\browser\index.html'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\@sindresorhus\jimp-cee242d2\fonts\open-sans\open-sans-16-white\open-sans-16-white.fnt'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\atm_gcc_atomic.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\atm_gcc_sync.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\atm_windows.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\atm.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\byte_buffer_reader.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\byte_buffer.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\compression_types.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\connectivity_state.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\exec_ctx_fwd.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\fork.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\gpr_slice.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\gpr_types.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\grpc-a812246f\deps\grpc\include\grpc\impl\codegen\grpc_types.h'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\protobufjs-a87c0065\examples\websocket\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\protobufjs-a87c0065\examples\websocket\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\protobufjs-a87c0065\examples\websocket\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\protobufjs-a87c0065\examples\websocket\server.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\crystal\Desktop\assistant-relay-master\node_modules\.staging\protobufjs-a87c0065\examples\websocket'
npm WARN assistant-relay@2.1.1 No repository field.

npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/notmasteryet/jpgjs.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\crystal\AppData\Roaming\npm-cache\_logs\2018-12-25T08_35_56_757Z-debug.log

C:\Users\crystal\Desktop\assistant-relay-master>

**Comment by ryancasler** [comment]
What node version are you running?  Version 8.11 is recommended.

**Comment by greghesp** [comment]
Please try node v8
