### ISSUE TITLE
Question/Feature Request: Continued Conversation

### ISSUE THREAD

**Issue by ryancasler** [greghesp/assistant-relay#72]
I was wondering about "continued conversation" and the broadcast commands.  Now that broadcasts allow for responses, any plans to add that to Assistant Relay so that response could be parsed into a command?  Just thought I'd ask and see if you had given that any thought.  Thanks!

**Comment by greghesp** [comment]
Are you sure this doesn't already work?  I've just tested it

```
{
 "command": "How tall is Obama?",
 "user": "greg"
}

{
    "response": "1.85 metres.",
    "audio": "http://localhost:9001/audio?v=86",
    "success": true
}
```

```
{
 "command": "How old is he?",
 "user": "greg"
}

{
    "response": "57 years old.",
    "audio": "http://localhost:9001/audio?v=46",
    "success": true
}
```

**Comment by greghesp** [comment]
Did you get this sorted @ryancasler ?

**Comment by ryancasler** [comment]
Ah...I see what you are saying....what I meant was that a broadcasts allows for users to reply to the broadcast.  I was just wondering if there was any way to get that response into Relay and then parse that for some other action.  Probably well beyond the scope of what you want to do.
