### ISSUE TITLE
tell me about my day

### ISSUE THREAD

**Issue by irabeamte2** [greghesp/assistant-relay#73]
i am trying to get 'tell me about my day' to work. is this command not supported?

curl -d '{"command":"tell me about my day", "user":"leondutton", "converse":"true"}' -H "Content-Type: application/json" -X POST http://192.168.0.15:3200/assistant
{"audio":"http://http://192.168.0.15:3200/audio?v=31","success":true}
no response from google

stupid jokes work
curl -d '{"command":"tell me a joke", "user":"leondutton", "converse":"true"}' -H "Content-Type: application/json" -X POST http://192.168.0.15:3200/assistant
{"audio":"http://http://192.168.0.15:3200/audio?v=88","response":"What do you call a labrador that becomes a magician?\nA labracadabrador 🐶 🎩 ✨","success":true}
(these jokes are really bad right?)

am I missing something?

**Comment by datayeah** [comment]
Good guess, but then i'm wondering why it's able to turn on and off my lightbulbs, since these are part of my individual home, too. I will have a deeper look at the source code of the relay in the next days to understand how it's passing data over to the Google Home.

**Comment by njtrettel** [comment]
hm. that's interesting. if my response were true, i wouldn't have expected your lights to turn on/off.

**Comment by coenboomkamp** [comment]
Not entirely true @njtrettel. I got the same issue, in my case in Dutch:

**This works:** 
"Tell me a joke" - Converse
curl -d '{"command":"Vertel me een grap", "user":"coen", "converse":"true"}' -H "Content-Type: application/json" -X POST http://192.168.1.2:3000/assistant

Which gives back:
{"response":"Komt ie\nWaarom stond de kok te zingen tijdens het koken?\nHij was behoorlijk in de olie 🍺😄","audio":"http://192.168.1.2:3000/audio?v=74","success":true}

That works, and it is also played on my Google Home Mini

**This doesn't work:**
curl -d '{"command":"Hoe ziet mijn dag eruit", "user":"coen", "converse":"true"}' -H "Content-Type: application/json" -X POST http://192.168.1.2:3000/assistant

Which gives this back:
{"audio":"http://192.168.1.2:3000/audio?v=87","success":true}

When i actually open that in my browser, the audio file is the exact response that i expect, it's an audio file that tells me about my day.

But it does not play on my Google Home Mini, any idea how this is possible?

@irabeamte2 @datayeah You can fix the double http:// by removing it from the config.json. Just put your ip there and port.

Thanks sofar,

Coen

**Comment by coenboomkamp** [comment]
@ryancasler I wouldn't mind if it replied to both my Google Home mini's. Still don't understand why it can't work for "tell me about my day".

Like i said before, it does give back a URL which contains the audio file telling me about my day.

_> curl -d '{"command":"Hoe ziet mijn dag eruit", "user":"coen", "converse":"true"}' -H "Content-Type: application/json" -X POST http://192.168.1.2:3000/assistant
> 
> Which gives this back:
> {"audio":"http://192.168.1.2:3000/audio?v=87","success":true}
> 
> When i actually open that in my browser, the audio file is the exact response that i expect, it's an audio file that tells me about my day._

**Comment by ryancasler** [comment]
I'm just telling you why, it's not like we have any control over what Google does.  It's not an Assistant Relay limitation but a Google assistant one.

**Comment by greghesp** [comment]
Ryan is correct, it's a limitation from Google unfortunately.

If you ask to tell you above your day, you're asking AR for that information so AR will return the audio (if Google supports it). Same way by if you ask your GH in the kitchen to do that command, you wouldn't expect it to broadcast it through the house

Also asking to play music on devices is limited by Google

**Comment by njtrettel** [comment]
@ryancasler very informative, thanks
