### ISSUE TITLE
Relay Returns Success But Nothing Happens

### ISSUE THREAD

**Issue by neuman** [greghesp/assistant-relay#74]
Seems l have everything set up correctly because I get success messages back with appropriate audio urls, but nothing happens on any of my devices. 

Thanks for your help!

**Comment by austinhag** [comment]
I had this issue and resolved it by disabling ipv6 on my wifi router.  It appears that with ipv6 enabled, google home uses those addresses and does not think the assistant relay is on the same network as your google home devices.

**Comment by greghesp** [comment]
Likely the about. Disable ipv6 on your router (sorry, nothing to do with AR, was a decision Google made)
