### ISSUE TITLE
Doubling of http

### ISSUE THREAD

**Issue by austinhag** [greghesp/assistant-relay#76]
There is a doubling of the "http://" text in the json response as the sample baseUrl variable in config.json includes the http and the statement in assistant.js adds another http to the string. If entered as outlined, it will produce a response with duplicate http like the below:

{
"audio": "http://http://192.168.1.167:3000/audio?v=76",
"success": true
}

**Comment by coenboomkamp** [comment]
I fixed this by removing the http:// from the config.json.
Just use IP address and port

**Comment by austinhag** [comment]
Perfect. Thanks for making the change.
