### ISSUE TITLE
how to setup without a browser ?

### ISSUE THREAD

**Issue by kiai72** [greghesp/assistant-relay#77]
hello, in don't have desktop/browser installed. should'nt there be a option to open the url manually on another machine ? But i don't know the URL i have to open - see my session log:

pi@retropie:~/assistantrelay $ npm run start

> assistant-relay@2.1.1 start /home/pi/assistantrelay
> node server/app.js

Opening OAuth URL. Return here with your code.
Paste your code:

**Comment by ryancasler** [comment]
You can run from putty through SSH on a device that does have a browser.  It will just give you the link you have to launch and then allow you to paste the code in.

**Comment by kiai72** [comment]
> You can run from putty through SSH on a device that does have a browser. It will just give you the link you have to launch and then allow you to paste the code in.

that's exactly what i did: assistant-relay is running on rapsberry pi (rapsbian stretch). i connect to the pi via putty - and start it in the putty session. But all it says is:
   Opening OAuth URL. Return here with your code.
   Paste your code:
It does not give me the link!

**Comment by ryancasler** [comment]
Does for me. Just re-set up a few days ago.  You have your JSON file where you are supposed to and have your config file set up correctly?

**Comment by greghesp** [comment]
I'd suggest setting this up again as it should put a link in the console. If not, something isn't right with your authorization setup
