### ISSUE TITLE
Time is off by one hour

### ISSUE THREAD

**Issue by coenboomkamp** [greghesp/assistant-relay#78]
Hi all,

I got a time issue. I'm running assistant-relay from a docker container from [KMLucy](https://github.com/kmlucy/docker-assistant-relay) on my NAS. The log of the docker container is 1 hour behind. Please read the issue that i made [here](https://github.com/kmlucy/docker-assistant-relay/issues/1) too.

Weird thing is, the docker command to get the date, is giving the correct time:
_$ docker run --rm -it -e TZ=Europe/Amsterdam kmlucy/docker-assistant-relay date
Fri Jan 25 20:25:10 CET 2019_

At the moment of testing it was 20:25, and i tested some quiet hour settings:

"start": 23, "end": 21
_Dude, chill, it's quiet time!_

"start": 23, "end": 20
_Dude, chill, it's quiet time!_

"start": 23, "end": 19
_{"audio":"http://192.168.1.2:3000/audio?v=61","success":true}_

Seems to me that it's not correct, it should have send the command to the Google Home at the 23-20 setting too i guess?

Hope anyone can help me out!

**Comment by greghesp** [comment]
I think this is technically working correctly although a bit confusing. I'll see if I can tweak it to make it work a bit better.

I assume it's rounding the time down to 20 because it's before half past

**Comment by greghesp** [comment]
Will fix for version 3. Removing the hours and adding in proper HH:mm support

**Comment by greghesp** [comment]
Fixed in V3
