### ISSUE TITLE
Add support for device instance

### ISSUE THREAD

**Issue by DJTSmith18** [greghesp/assistant-relay#79]
I was wondering if it would be possible to implement "device instance" and "device id" within the assistant relay?
 
https://developers.google.com/assistant/sdk/reference/device-registration/model-and-instance-schemas#example

I had been working on a previous Magic Mirror project with an assistant module.  I was able to create a device id and OAuth credentials for my device.  then I would create a token  with the tool in the SDK.

this permitted the "Magic Mirror" to appear in my Home app in my phone and let the "Magic Mirror" answer personalised information and most importantly start Routines.

Starting routines with the assistant relay would be a game changer!  I could use an insteon light switch to trigger a routine, that would be awesome!

any help would be great!

thanks

**Comment by DJTSmith18** [comment]
I have routines that set light switch brightness settings, change the color of my led strips and starts playing music on one of my Chromecast speaker groups.  Nothing actually happens on the actual device.  I can trigger this routine from any Google home device or phone with the same results. And I could trigger this from the Google assistant module in magic mirror.  There are many uses for this.  I have smart switches everywhere and would like to have them trigger a routine without having to yell out to my Google home when everyone is sleeping

**Comment by DJTSmith18** [comment]
Let's say your morning routine is "play podcast to kitchen Chromecast". Nothing actually happens on the relay itself

**Comment by ryancasler** [comment]
It doesn't work that way.  When you do that, the device that initiated it is doing the actual playing.  It allows you to stop the stream on the other device.  But the Assistant Relay device doesn't have the support for audio, so it can't stream it to the other Google Home device.

**Comment by DJTSmith18** [comment]
ryancasler I do not believe you are correct, the google assistant device does no playing what so ever in this case.  it only sends a command to the chromecast to point it to the streaming endpoint.  the chromecast itself connects directly to, lets say, google play music and starts the streaming.  the only audio that the assistant device actually processes is the response  "OK, Playing music on chromecast".  Try asking your google home to play music on a chromecast then "unplug your google home immediately"  the music will still be playing on the chromecast. 

an other example, use an music app on your phone, start a stream to your chromecast and immediately turn off your phone, stream continues.  Chromecasts never stream anything locally from one device to an other, the only exception to this is android screen and audio casting.

I had the exact same behavior using the assistant python sdk on a RPI it would not run routines, could not cast music until I added a device ID that I had registered on the google cloud dev portal. then miraculously everything started working. 

I am just supprised that this cannot be implemented here for the sole reason of not supporting audio.

**Comment by kebel87** [comment]
> I had the exact same behavior using the assistant python sdk on a RPI it would not run routines, could not cast music until I added a device ID that I had registered on the google cloud dev portal. then miraculously everything started working.

I don’t remember doing when I configured my assistant and I don’t see it in the instructions. Can you get into more details on how to do so? Thanks!

**Comment by louis-lau** [comment]
This would be awesome.

**Comment by greghesp** [comment]
I'll have a look at this. I haven't been too active with Assistant Relay for car reasons but I'll see what I can do

**Comment by greghesp** [comment]
@DJTSmith18  Have you got any more information on this?  I've had a look around and I can't see how this works?

**Comment by MikolFr** [comment]
Hi all,
if I well understand, adding device id should allow routine start from relay. I made two tests:

- by adding a device and declaring it in config.json
- or with the initial google assistant project

but in both cases, I can't start routines. My "device" is available in Home app and when I ask something, I can check that it was well sent from my device.

Perhaps that it's specific to some device models ?

@DJTSmith18 , do you remember if something specific need to be set ?!
Thanks

**Comment by antro31** [comment]
+1
I can't figure out why it does not work when I send "Play music on tv" to assistant relay where this works when I tell it to my google home mini. 
This would help me a lot. 

Thanks.

**Comment by greghesp** [comment]
@antro31  This is an SDK limitation, not an Assistant Relay one

**Comment by antro31** [comment]
OK. Then maybe you should document this in the main page. Thanks for your reply anyway. Good job for this!

**Comment by greghesp** [comment]
I need to spend some time wrapping my head around this as I can't understand how to integrate it.  I'll see whats possible for V3

**Comment by greghesp** [comment]
@DJTSmith18  Which module were you using?  I've got the device instance of Assistant Relay appearing in my Google Home app, but I cannot get it to trigger routines.

**Comment by ryancasler** [comment]
I concur.  I've not been able to find anything in the Assistant SDK which support routines.  I've tried to use routines on the last couple versions (including 3.1) and Assistant always returns an error.

**Comment by greghesp** [comment]
I'm going to close this down as I don't think its possible.  If it turns out im wrong, please reopen, comment or open a new request

**Comment by greghesp** [comment]
I'm going to close this down as I don't think its possible.  If it turns out im wrong, please reopen, comment or open a new request
