### ISSUE TITLE
Make "/custom" endpoint allow GET requests and return response

### ISSUE THREAD

**Issue by bendews** [greghesp/assistant-relay#8]
As per title, I think it makes sense to have the /custom endpoint accept GET requests, and return the response to the query/command.

This also opens up lots of possibilities with SmartThings/WebCoRE to use the responses for other purposes.

**Comment by qreeves** [comment]
Or use IFTTT via WebHooks!

**Comment by ryancasler** [comment]
Or, how about that's not what this was designed to do.  It was designed to provide a way to issue broadcasts to Google home. If you want to issue a command to Google home to get information, where are you going to issue the Get request from?  That's whats going to get the response.  What is IFTTT going to do with that information?  LOL. I think you guys have gone a little off scope.

**Comment by qreeves** [comment]
I misread the O.P. thinking it meant _issuing_ get requests, not receiving data from it.

**Comment by bendews** [comment]
@ryancasler I'm not sure if you were replying to me or the previous deleted comment before yours.
Note that this project is _assistant_-relay, and as per the documentation, is primarily a project to allow commands to be sent to Google Assistant. Broadcast functionality is a very important feature additional to that. 

I would say receiving the response to those commands is also fairly important (although understandably a low priority at the moment), as the Google home integrates with many different services and platforms and holds lots of data which is useful in lots of situations, which may be very difficult to get otherwise.

As to "where are you going to issue the Get request from?", both SmartThings and WebCoRE support sending GET requests and parsing the response to take actions, as does almost every other platform out there. As an example I have a WebCoRE piston that queries a government resource to check if there is a public holiday falling on a rubbish pickup day and modifies my SmartThings notification schedule if so.

**Comment by bendews** [comment]
Oops, accidentally closed the feature request 😆

**Comment by ryancasler** [comment]
What information are you trying to get from the assistant that you want passed back to WebCore?

**Comment by Harel-M** [comment]
Hi, I also agree that getting the assistant's answer as the HTTP response is a good feature.
It can be used for syncing status of Home Control devices.
Currently with the script you can start/stop a device (by sending "turn on X" for example).
but when sending ("is X on?") I encounter two problems:
1) I don't get the assistant's answer as a response to the HTTP request. I only get the command what I've send - kind of redundant.
2) for some reason the answers for this kind of questions are not showing even on the console - it's like the assistant is not answering (or probably just sends web search result that is not showing) - while when typing/saying the exact same thing on the phone or google home it's answers properly - I don't understand why.

If we'll get the assistant's answer, home control scripts will be able to search the status in the answer and update themselves accordingly.
This opens a whole new way to control everything that can be controlled by the google assistant on other automation systems...

Thanks,

**Comment by greghesp** [comment]
I'm going to close this for now.  I've begun adding this functionality into V2.0 which is available for testing.  It's not fully featured, so dont' run it as the main relay

**Comment by bendews** [comment]
Just had a look at the feature set for V2.0, very nice @greghesp!
