### ISSUE TITLE
Getting ENOENT error when running

### ISSUE THREAD

**Issue by MrGudgeon** [greghesp/assistant-relay#81]
This install was working fine about a week ago and now isn't working. Only change since then was a power off of the raspberry pi, then back on.

These are the errors i am getting.
1|assistan | Error: ENOENT: no such file or directory, open 'server/configurations/config.json'
1|assistan |     at Object.fs.openSync (fs.js:646:18)
1|assistan |     at fs.writeFileSync (fs.js:1291:33)
1|assistan |     at FileSync.read (/home/pi/assistant-relay/node_modules/lowdb/adapters/FileSync.js:46:9)
1|assistan |     at LodashWrapper.db.read (/home/pi/assistant-relay/node_modules/lowdb/lib/main.js:32:21)
1|assistan |     at module.exports (/home/pi/assistant-relay/node_modules/lowdb/lib/main.js:51:13)
1|assistan |     at Object.<anonymous> (/home/pi/assistant-relay/server/configuration.js:7:12)
1|assistan |     at Module._compile (module.js:635:30)
1|assistan |     at Object.Module._extensions..js (module.js:646:10)
1|assistan |     at Module.load (module.js:554:32)
1|assistan |     at tryModuleLoad (module.js:497:12)

I found that ENPENT means that the config.json file doesn't exist, but it does, in that exact file location from the log.

Not sure where to look at next. Does anyone have any ideas?

Node version: v8.9.0

Thanks!

**Comment by greghesp** [comment]
Can you try V3 and reopen if its still an issue please?
