### ISSUE TITLE
Possible to run remotely?

### ISSUE THREAD

**Issue by JCharante** [greghesp/assistant-relay#82]
I apoligize if this has been asked before, but I couldn't find a relevant issue.

I'm wondering if it is possible to use assistant-relay remotely, as in, run it in a VPS on the cloud, rather than on a device connected to the same router as the google home device.

assistant-relay works wonderfully when the device running assistant-relay is connected to the same wifi network (as the google home device), but unfortunately commands do not go through when it is not. Is there any work around for this other than to have a device running assistant-relay connected to the same wifi network?

**Comment by kebel87** [comment]
I guess you are discording a site-2-site VPN connection between your home and your VPS environment?

**Comment by JCharante** [comment]
@kebel87 Not necessarily, I'm more looking into how feasible this is. Is it a matter of getting the google home device to be publically accessible to the internet from the perspective of the VPS, or as you said would we have to run a VPN connection between the google home device and the VPS? If the latter, then is the only way to do so by using another device to create a hotspot which drives all its traffic to the VPN?

**Comment by ryancasler** [comment]
Not at all.  Your Assistant Relay device must be on the same network as the Google Home devices to which you want to broadcast.  It will detect that you aren't on the same network and won't play.  I even have to keep IPv6 support on my router off.  Turning it on makes all my GH devices think they aren't on the same network as my assistant relay device.

**Comment by greghesp** [comment]
This isn't something thats supported with AR. I believed Google made some changes that means that assistant devices on work together on the same network
