### ISSUE TITLE
"Sorry, you can only do this when you are connected to that wifi network"

### ISSUE THREAD

**Issue by DanielBaulig** [greghesp/assistant-relay#84]
I am trying to use Assistant Relay to enable/disable Do not Disturb mode on Google Home devices in my home in response to signals I get from SmartThings.

I am using the following command:
"Activate Do Not Disturb on ${deviceName}"

The post request completes successfully, but the audio message produced says "Sorry, you can only do this when you are connected to that wifi network. Try again once you're connected."
When I try to execute the same command from the Google Assistant app on my phone I get the same response. Note that regular broadcasts through Assistant Relay work as expected.

I assume that this is something that Google needs to change on their end, correct? Or is there a way that Assistant Relay can "prove" that it actually is on the same network (since it is)? Or some other way to make this work?

Thanks!

**Comment by greghesp** [comment]
If you're getting the same issue on your phone, it'd suggest there is a local issue somewhere on your network I'd imagine.
