### ISSUE TITLE
 Exit status 132 on rpi zero W

### ISSUE THREAD

**Issue by kiai72** [greghesp/assistant-relay#86]
i can't get to work on rpi zero W (raspbian stretch lite) - see debug log further down.

i have a lot of other node-apps running. So i doubt it's a node -problem.
it works on my rpi3b+ (with the same node-version) - but not on my zero W. 

0 info it worked if it ends with ok
1 verbose cli [ '/home/pi/.nvm/versions/node/v8.15.0/bin/node',
1 verbose cli   '/home/pi/.nvm/versions/node/v8.15.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle assistant-relay@2.1.1~prestart: assistant-relay@2.1.1
6 info lifecycle assistant-relay@2.1.1~start: assistant-relay@2.1.1
7 verbose lifecycle assistant-relay@2.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle assistant-relay@2.1.1~start: PATH: /home/pi/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/assistant-relay-master/node_modules/.bin:/home/pi/.nvm/versions/node/v8.15.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle assistant-relay@2.1.1~start: CWD: /home/pi/assistant-relay-master
10 silly lifecycle assistant-relay@2.1.1~start: Args: [ '-c', 'node server/app.js' ]
11 silly lifecycle assistant-relay@2.1.1~start: Returned: code: 132  signal: null
12 info lifecycle assistant-relay@2.1.1~start: Failed to exec start script
13 verbose stack Error: assistant-relay@2.1.1 start: `node server/app.js`
13 verbose stack Exit status 132
13 verbose stack     at EventEmitter.<anonymous> (/home/pi/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/pi/.nvm/versions/node/v8.15.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid assistant-relay@2.1.1
15 verbose cwd /home/pi/assistant-relay-master
16 verbose Linux 4.14.83-aufs
17 verbose argv "/home/pi/.nvm/versions/node/v8.15.0/bin/node" "/home/pi/.nvm/versions/node/v8.15.0/bin/npm" "run" "start"
18 verbose node v8.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 132
22 error assistant-relay@2.1.1 start: `node server/app.js`
22 error Exit status 132
23 error Failed at the assistant-relay@2.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 132, true ]

**Comment by kiai72** [comment]
it's a grpc problem: here's how to fix it: https://github.com/googleapis/nodejs-speech/issues/12

**Comment by ryancasler** [comment]
I don't believe assistant relay will work on a zero w since it uses the embedded assistant sdk.

https://developers.google.com/assistant/sdk/guides/library/python/embed/setup

**Comment by kiai72** [comment]
> I don't believe assistant relay will work on a zero w since it uses the embedded assistant sdk.

it does work on the zero W! - check post #2

**Comment by szh** [comment]
Per https://developers.google.com/assistant/sdk/guides/service/python/embed/setup?hardware=rpi

![image](https://user-images.githubusercontent.com/546965/107991930-a0068180-6fa5-11eb-8b78-7b22d42c59c7.png)


> I don't believe assistant relay will work on a zero w since it uses the embedded assistant sdk.
> 
> https://developers.google.com/assistant/sdk/guides/library/python/embed/setup

**Comment by ryancasler** [comment]
I believe i referenced the wrong library.  That one was deprecated 2 years ago.

**Comment by szh** [comment]
@ryancasler It looks to me that the one that's deprecated is the one that doesn't support the Zero:

![image](https://user-images.githubusercontent.com/546965/108141326-817db480-7091-11eb-9c0c-31505ab8dd41.png)

vs.
![image](https://user-images.githubusercontent.com/546965/108141363-95291b00-7091-11eb-92ec-3b34ca4b19e1.png)


Which does assistant-relay use?

**Comment by ryancasler** [comment]
https://github.com/endoplasmic/google-assistant

That is the library that it uses.
