### ISSUE TITLE
"/broadcast" endpoint requires valid user

### ISSUE THREAD

**Issue by bendews** [greghesp/assistant-relay#9]
The broadcast endpoint requires a user to be defined in order to successfully use a preset broadcast.

The SmartThings device type does not allow a user to be specified.

For now I have removed the checkUser() IF statement (which falls back to using the first defined user, per sendTextInput()) to workaround the requirement.

**Comment by greghesp** [comment]
This isn't a bug.  Some of the preset broadcasts require a user.  You need to pass the user as the 2nd parameter
