### ISSUE TITLE
Works with nest

### ISSUE THREAD

**Issue by mschwartz** [greghesp/assistant-relay#92]
Works with nest is going to end.

What does that mean for this code?

**Comment by ogiewon** [comment]
Who knows?  WWN really has nothing to do with Google Assistant. Same parent company, yes. But two different products. 

I am hopeful that Google enhances Google Assistant and that Assistant Relay also receives the same enhancements. However, Google could choose to shut this down altogether, if they want to. It’s hard to tell what they’re thinking these days.
