### ISSUE TITLE
any way to enable multi user support?

### ISSUE THREAD

**Issue by andres934** [greghesp/assistant-relay#95]
the project is working great, but i was wondering the way to instead of asking for login and server start, be able to send the oauth token directly on the start depending on the logged user, or maybe be send it on command POST, so the server can work with multiple users at once.

Has anyone accomplish this??

**Comment by greghesp** [comment]
It already supports multi users
https://github.com/greghesp/assistant-relay#creating-users

Just stick the .json file in the appropriate folder with a suitable name, and then set the user to the name of that file in your api call
