### ISSUE TITLE
No Browser and no Url

### ISSUE THREAD

**Issue by chriscolden** [greghesp/assistant-relay#96]
Hi,

I'm running this on centos 7 which i run headless. Running assistant-relay states it has launched a browser even though one is not available. It also doesn't spit out the url I need to use to do it manually.

I'm a bit stuck can anyone help?

Chris

**Comment by jkpe** [comment]
I had this issue, I removed node v10 and installed node v8

**Comment by chriscolden** [comment]
I'll check but I'm sure I already downgraded as it wouldnt start in node v10

**Comment by chriscolden** [comment]
Yeah it's v8.11.0

**Comment by jkpe** [comment]
I am version v8.16.0, in case that makes any difference

**Comment by greghesp** [comment]
It might be linked to #108 
Could you try this?

**Comment by greghesp** [comment]
Could you try V3 now please?
