### ISSUE TITLE
Assistant Relay as Hass.io Add-On

### ISSUE THREAD

**Issue by JoshuaSG** [greghesp/assistant-relay#97]
Would it be possible to package Assistant Relay as an Hass.io add-on?

**Comment by greghesp** [comment]
Has anyone got any experience with Hass.io?  I've never used it, and I can't seem to find any information on how to create an add-on?

**Comment by Apipa169** [comment]
I have not a lot experience with it, but I'm trying to get it to work as a Hass.io addon. 

I have it running, but after a restart it loose the config. Currently this is expected behaviour, but it needs to be solved before people can use it. Can you tell me where the user info and authentication is being stored? I was not able to figure this out yet.

**Comment by greghesp** [comment]
It does all the configuration details in ./bin/config.json

**Comment by Apipa169** [comment]
Is that the only location where configuration is stored? I have configured Assistant Relay, saved the config.json and reinstalled everything again. If I'm putting the config.json in the right folder just before I start I'm getting the following error:

`Auth error:TypeError: Cannot read property 'access_token' of undefined
0|www  | { Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: Cannot read property 'access_token' of undefined
0|www  |     at Object.exports.createStatusError (/assistant_relay/node_modules/grpc/src/common.js:91:15)
0|www  |     at ClientDuplexStream._emitStatusIfDone (/assistant_relay/node_modules/grpc/src/client.js:233:26)
0|www  |     at ClientDuplexStream._receiveStatus (/assistant_relay/node_modules/grpc/src/client.js:211:8)
0|www  |     at Object.onReceiveStatus (/assistant_relay/node_modules/grpc/src/client_interceptors.js:1311:15)
0|www  |     at InterceptingListener._callNext (/assistant_relay/node_modules/grpc/src/client_interceptors.js:568:42)
0|www  |     at InterceptingListener.onReceiveStatus (/assistant_relay/node_modules/grpc/src/client_interceptors.js:618:8)
0|www  |     at /assistant_relay/node_modules/grpc/src/client_interceptors.js:1127:18
0|www  |   code: 14,
0|www  |   metadata: Metadata { _internal_repr: {}, flags: 0 },
0|www  |   details:
0|www  |    'Getting metadata from plugin failed with error: Cannot read property \'access_token\' of undefined' }`

**Comment by greghesp** [comment]
Are you using v3?

**Comment by Apipa169** [comment]
I'm using v3.0.3

**Comment by greghesp** [comment]
Yep. Its just the config.json file.  It does store the audio responses in ./bin/audio-responses but thats it

**Comment by Apipa169** [comment]
I have tried something different. I was hoping it would fix it, but it doesn't.

What I do now: Before I start I'm changing the path of the config in the following files:
./helpers/server.js
./helpers/assistant.js
./helpers/auth.js
./helpers/misc.js
./routes/index.js
./server.js
./bin/www

Then I'm running AR which works fine, including the new config file path. But after a restart of my addon I'm getting the error I mentioned above along with a few similar errors. Nothing happened to the config file and the .js files are still looking at the new location.

_I'm using a different location for the config file to save it. All other files get lost on a reboot or upgrade. But even with the default location I'm getting these errors._

**Comment by greghesp** [comment]
I don't know enough about Hass to know what would cause that.

Does it just require a Docker release, or is there more to it?

**Comment by Apipa169** [comment]
A docker release is not required for me, but I think it can be very useful for some users.

**Comment by ryancasler** [comment]
The only authentification that has to be passed to Assistant Relay is the username in the HTTP command. You don't have to pass a secret or a token or something.  Maybe that's where it is falling down.  It's simple HTTP Post requests to the relay server.  If you are running on the same server as hass.io then I can see that a docker container would probably be easier.  I've build one for the latest version.  

https://hub.docker.com/r/ryan780/assistant-relay-v3

You can find it there with instructions to build and run.

**Comment by Apipa169** [comment]
That is not the issue, the error occurs when I run the addon (Alpine docker container) for the second time. This is before I send any HTTP commands.

But thanks for creating a docker image, I'll have a look if that runs better!

**Comment by ryancasler** [comment]
Why are you editing the config.json file.  That's what I don't understand.  You are trying to make this more complicated than it needs to be.  You cannot edit the json file.  You have to go through the web setup because you have to store the token with the ID/Secret for your account.  That will be unique every time you do it.

**Comment by Apipa169** [comment]
I'm not editing the config.json,I just change the location to make it easier to keep the file in a volume. I know this can be done much easier in docker, but in Hassio this is the easiest way.

In the dockerfile I'm changing the files mentioned above to change the path of the config.json.

**Comment by Apipa169** [comment]
It's solved and runs great!

https://github.com/Apipa169/Assistant-Relay-for-Hassio

@JoshuaSG Are you still looking for this addon? Would be great if you can test it on your system and give me some feedback! Thanks!

**Comment by JoshuaSG** [comment]
@Apipa169 Awesome, thanks for your work! Looks like I have the addon up and running, but I think I messed up something in setting up the user, basic commands work but I'm unable to interact with my local devices.

Edit: Looks like it may be a limitation of the Assistant API...

**Comment by Apipa169** [comment]
@JoshuaSG Great to hear! 

There is indeed a limitation at the Google API. I’m using it just for broadcasts at the moment.

**Comment by ryancasler** [comment]
You can issue broadcasts or commands to interact with some other Google Home connected devices, such ax fans and lights, that would not otherwise be able to be connected to HASS.io.  But you cannot control individual Google Home devices.  That is a limitation to the Google Assistant SDK.  It is not a full-service API to the Google Home infrastructure, unfortunately.

**Comment by greghesp** [comment]
Did this get implemented?  I'm not too familiar with Hass but I know there were a few Docker instances created.

**Comment by Apipa169** [comment]
Yes it is! Me and a few others have it running in Hassio :-)
